W5300 - SOCKET APIs: main.c File Reference
main.c File Reference
Detailed Description
W5300 example applications
This file shows how to use WIZnet SOCKET APIs and how to implement your internet application with W5300.
Author:
MidnightCow
Date:
11/25/2008
Version:
1.2.1
Revision History :
Date Version Author Description
24/03/2008 1.0.0 MidnightCow Release with W5300 launching
01/05/2008 1.0.1 MidnightCow Modify 'w5300.c'
15/05/2008 1.1.0 MidnightCow Modify 'w5300.c', 'w5300.h', and 'socket.c'.
04/07/2008 1.1.1 MidnightCow Modify 'socket.c'
08/08/2008 1.2.0 MidnightCow - Solve unmatched-link between the descripion and the source code.
Modify 'w5300.c' & 'socket.c'
11/25/2008 1.2.1 Bongjun - Fixed the bug in close()
Modify 'socket.c'
The Main() includes the example program of W5300 such as
loopback_tcps()
loopback_tcpc()
loopback_udp()
Definition in file main.c.
#include "main.h"
#include "xscale.h"
#include "socket.h"
Functions
void loopback_tcps (SOCKET s, uint16 port, uint8 *buf, uint16 mode)
"TCP SERVER" loopback program.
void loopback_tcpc (SOCKET s, uint8 *addr, uint16 port, uint8 *buf, uint16 mode)
"TCP CLIENT" loopback program.
void loopback_udp (SOCKET s, uint16 port, uint8 *buf, uint16 mode)
UDP loopback program.
void Main ()
It executes example program such as loopback_tcps(), loopback_tcpc(), and loopback_udp().
Function Documentation
void loopback_tcpc (SOCKET s, uint8 * addr, uint16 port, uint8 * buf, uint16 mode)
"TCP CLIENT" loopback program.
It initilizes SOCKET as TCP mode and try to connect to AX1. If a connection is accepted by AX1, it receives data from AX1 and sends the data to AX1.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] addr IP address of the PC that runs AX1 ("TCP SERVER" IP address)
[in] port listen port number of AX1 ("TCP SERVER" listen port number)
[in,out] buf A buffer to be used for loopback data
[in] mode SOCKET options
The below image shows the flow diagram of "TCP CLIENT".
<The flow of TCP CLIENT>
Definition at line 218 of file main.c.
References close(), connect(), disconnect(), getSn_IR(), getSn_RX_RSR(), getSn_SSR(), recv(), send(), setSn_IR(), Sn_IR_CON, Sn_MR_TCP, SOCK_CLOSE_WAIT, SOCK_CLOSED, SOCK_ESTABLISHED, SOCK_INIT, and socket().
Referenced by Main().
void loopback_tcps (SOCKET s, uint16 port, uint8 * buf, uint16 mode)
"TCP SERVER" loopback program.
It initilizes SOCKET as TCP mode and listens to a connection request of AX1. If a connection is accepted, it receives data from AX1 and sends the data to AX1.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] port listen port number
[in,out] buf A buffer to be used for loopback data
[in] mode SOCKET options
The below image shows the flow diagram of "TCP SERVER".
<The flow of TCP SERVER>
Definition at line 162 of file main.c.
References close(), disconnect(), getSn_IR(), getSn_RX_RSR(), getSn_SSR(), listen(), recv(), send(), setSn_IR(), Sn_IR_CON, Sn_MR_TCP, SOCK_CLOSE_WAIT, SOCK_CLOSED, SOCK_ESTABLISHED, SOCK_INIT, and socket().
Referenced by Main().
void loopback_udp (SOCKET s, uint16 port, uint8 * buf, uint16 mode)
UDP loopback program.
It initilizes SOCKET as UDP mode. If it receives data from any AX1, it sends the data to the AX1.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] port listen port number
[in,out] buf A buffer to be used for loopback data
[in] mode SOCKET options
The below image shows the flow diagram of UDP or IPRAW.
<The flow of UDP or IPRAW>
Definition at line 274 of file main.c.
References close(), getSn_RX_RSR(), getSn_SSR(), recvfrom(), sendto(), Sn_MR_UDP, SOCK_CLOSED, SOCK_UDP, and socket().
Referenced by Main().
void Main ()
It executes example program such as loopback_tcps(), loopback_tcpc(), and loopback_udp().
It initilizes MCU, serial port and W5300 and executes 6 loopback_tcps() which have same listen port number, 1 loopback_tcpc(), and 1 loopback_udp().
Definition at line 55 of file main.c.
References close(), getGAR(), getPDHAR(), getPSIDR(), getSHAR(), getSIPR(), getSUBR(), iinchip_init(), loopback_tcpc(), loopback_tcps(), loopback_udp(), pppinit(), pppterm(), setGAR(), setSHAR(), setSIPR(), setSUBR(), and sysinit().