W5300 - SOCKET APIs: include/socket.h File Reference
include/socket.h File Reference
Detailed Description
WIZnet SOCKET API function definition
For user application, WIZnet provides SOCKET API functions which are similar to Berkeley SOCKET API.
Author:
MidnightCow
Date:
11/25/2008
Version:
1.2.1
Revision History :
Date Version Author Description
24/03/2008 1.0.0 MidnightCow Release with W5300 launching
15/05/2008 1.1.0 MidnightCow Refer to M_15052008.
Modify the warning code block in recv().
04/07/2008 1.1.1 MidnightCow Refer to M_04072008.
Modify the warning code block in recv().
08/08/2008 1.2.0 MidnightCow Refer to M_08082008.
Modify close().
11/25/2008 1.2.1 Bongjun Refer to M_11252008.
Modify close().
Definition in file socket.h.
#include "types.h"
#include "w5300.h"
Functions
uint8 socket (SOCKET s, uint8 protocol, uint16 port, uint16 flag)
Open a SOCKET.
void close (SOCKET s)
Close a SOCKET.
uint8 connect (SOCKET s, uint8 *addr, uint16 port)
It tries to connect a client.
void disconnect (SOCKET s)
It tries to disconnect a connection SOCKET with a peer.
uint8 listen (SOCKET s)
It is listening to a connect-request from a client.
uint32 send (SOCKET s, uint8 *buf, uint32 len)
It sends TCP data on a connection SOCKET.
uint32 recv (SOCKET s, uint8 *buf, uint32 len)
It receives TCP data on a connection SOCKET.
uint32 sendto (SOCKET s, uint8 *buf, uint32 len, uint8 *addr, uint16 port)
It sends UDP, IPRAW, or MACRAW data.
uint32 recvfrom (SOCKET s, uint8 *buf, uint32 len, uint8 *addr, uint16 *port)
It receives UDP, IPRAW, or MACRAW data.
Function Documentation
void close (SOCKET s)
Close a SOCKET.
It closes a SOCKET and releases its all used resouces.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Note:
In TCP mode, if you disconnect a SOCKET using close(), a FIN packet won't be sent to the peer.
Warning:
In TCP mode, You'd better to call close() after disconect() for the safe terminating. Refer to Sn_SSR bug phase.
Definition at line 57 of file socket.c.
References getIINCHIP_TxMAX(), getSn_MR(), getSn_TX_FSR(), sendto(), setSn_CR(), setSn_IR(), Sn_CR_CLOSE, Sn_MR_TCP, Sn_MR_UDP, socket(), and wait_10ms().
Referenced by loopback_tcpc(), loopback_tcps(), loopback_udp(), and Main().
uint8 connect (SOCKET s, uint8 * addr, uint16 port)
It tries to connect a client.
It operates a SOCKET as "TCP CLIENT" and sends a connect-request(SYN packet) to "TCP SERVER".
It is valid only in TCP mode.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] addr IP address of "TCP SERVER"
[in] port Listen port number of "TCP SERVER".
Returns:
success - 1
fail - 0
Definition at line 86 of file socket.c.
References IINCHIP_WRITE(), setSn_CR(), Sn_CR_CONNECT, Sn_DIPR, and Sn_DPORTR.
Referenced by loopback_tcpc().
void disconnect (SOCKET s)
It tries to disconnect a connection SOCKET with a peer.
It sends a disconnect-request(FIN packet) to "TCP SERVER" or "TCP CLIENT".
It is valid only in TCP mode.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Definition at line 113 of file socket.c.
References setSn_CR(), and Sn_CR_DISCON.
Referenced by loopback_tcpc(), and loopback_tcps().
uint8 listen (SOCKET s)
It is listening to a connect-request from a client.
It operates a SOCKET as "TCP SERVER" and waits a connect-request(SYN packet) from a "TCP CLIENT".
It is valid only in TCP mode.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
success - 1
fail - 0
Definition at line 118 of file socket.c.
References getSn_SSR(), setSn_CR(), Sn_CR_LISTEN, and SOCK_INIT.
Referenced by loopback_tcps().
uint32 recv (SOCKET s, uint8 * buf, uint32 len)
It receives TCP data on a connection SOCKET.
It is used to read incoming data on a connection SOCKET.
It is valid only in TCP mode.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[out] buf A buffer for the imcoming data
The length of buf should be equal or greater than len + 1, in order to prevent the memory violation.
[in] len The byte length of the data in buf
Returns:
It returns the number of bytes received.
Note:
When receiving TCP data from a peer,
In case of Sn_MR_ALIGN = '1'
W5300 adds PACKET-INFO(2bytes lenght) in front of all received DATA(max Sn_MSSR lenght) packet in internal RX memory. The added PACKET-INFO contains the size of DATA packet. If the size of received DATA packet is odd number, 1 byte dummy data is added. The host should read this dummy data first and ignore it.
In case of Sn_MR_ALIGN = '0'
iichip receives only DATA packet without PACKET-INFO. Therefore, All size of the received data should be a even number.
Below shows the format of received TCP data.
<The format of received TCP data>
Warning:
Warning:
When SOCKETn is used only to receive data without transmitting data, the slow data receiving process by the host can cause internal RX memory full. In this case, even though W5300 window size (the maximum size of receivable data) is not '0', by misunderstanding the window size as '0', the peer does not transmit the data, and waits until window size is increased. It is the cause of decreasing data receiving performance of W5300. In order to solve the problem, the host processes the data received in internal RX memory first and notify the peer that the window size of W5300 is increased by received data size.
After Sn_CR_RECV command, add to the below code.
 if(getSn_RX_RSR(s) == 0)
 {
    setSn_TX_WRSR(s,1);
    IINCHIP_WRITE(Sn_TX_FIFOR(s),0x0000);
    setSn_CR(s,Sn_CR_SEND);
    while(!(getSn_IR(s) & Sn_IR_SENDOK));
    setSn_IR(s,Sn_IR_SENDOK);
 }
There is no need when SOCKETn is used to both receive and transmit data.
Definition at line 217 of file socket.c.
References getSn_IR(), getSn_RX_RSR(), IINCHIP_READ(), IINCHIP_WRITE(), MR, MR_FS, setSn_CR(), setSn_IR(), setSn_TX_WRSR(), Sn_CR_RECV, Sn_CR_SEND, Sn_IR_SENDOK, Sn_MR, Sn_MR_ALIGN, Sn_TX_FIFOR, and wiz_read_buf().
Referenced by loopback_tcpc(), and loopback_tcps().
uint32 recvfrom (SOCKET s, uint8 * buf, uint32 len, uint8 * addr, uint16 * port)
It receives UDP, IPRAW, or MACRAW data.
It is used to read incoming data and to store a destination information.
On the IPRAW SOCKET, the port parameter are ignored.
On the MACRAW SOCKET, the addr and port parameters are ignored, making recvfrom() equivalent to recv(). But, The destination and source information is included in front of buf.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[out] buf A buffer for the imcoming data
The length of buf should be equal or greater than len + 1, in order to prevent the memory violation.
[in] len The byte length of the data in buf
[out] addr An optional pointer to the address of destination.
[out] port An optional the port number of destination.
Returns:
It returns the number of bytes received.
Note:
When receiving data from a peer, W5300 adds the different PACKET-INFO in front of all received DATA(max Sn_MSSR lenght) packet in internal RX memory. The added PACKET-INFO contains basically the DATA packet size which length is 2bytes and contains extra information such as destination IP address according to SOCKETn mode.
If the size of received DATA packet is odd number, 1 byte dummy data is added. The host should read this dummy data first and ignore it.
In case of UDP mode
<The format of received UDP data>
Destination IP address and port number are stored respectively in the parameters addr and port. And DATA packet is stored in the parameter buf.
In case of IPRAW mode
<The format of received IPRAW data>
Destination IP address is stored in the parameter addr. And DATA packet is stored in the parameter buf.
In case of MACRAW mode
<The format of received MACRAW data>
Destination and source MAC, and type are stored in the parameter buf. But, CRC is ignored.
Warning:
Warning:
In case that free buffer size of internal RX memory is smaller than the size of receiving MAC RAW data,
some parts of un-acceptable PACKET-INFO and DATA packet of the MACRAW data can be saved in internal RX memory. This can cause the error in analyzing PACKET-INFO, and receiving correct MACRAW data. This problem is more likely to happen when internal RX memory gets close full.
This can be solved by ignoring some loss of MACRAW data.
By performing internal RX memory process as quick as possible, prevent the memory to be full
By receiving only its own MACRAW data, reduce the receiving burden.
Set the Sn_MR_MF bit of S0_MR by calling socket() with Sn_MR_MF flag
   socket(0,Sn_MR_MACRAW,0x1000,Sn_MR_MF);
In case that the free size of internal RX memory is smaller than 1528 -Default MTU(1514)+ PACKET-INFO(2)+DATA packet(8)+CRC(4)- close SOCKET 0. After closing the SOCKET0, Process all received MACRAW data and the reopen the SOCKET0.
For example,
   // Assume that you can process the MACRAW data by this function.
   void process_macraw_data(uint8* mac_data, uint32 len);
   // main example
   void main(void)
   {
      int32 remained_rsr = 0;
      int32 rsr = 0;
      int32 recv_len = 0;
      uint8 data_buf[2048];
      while(1)
      {
         switch(getSn_SSR(0))
         {
            case SOCK_MACRAW:
               rsr = getSn_RX_RSR(0);
               if(rsr > 0)
               {
                  // check the received size.
                  if(getIINCHIP_MaxRX(0) - rsr < 1528) // Abnormal
                  {
                     remained_rsr = rsr;
                     close(s);
                     while(remained_rsr > 0)           // Process all received data.
                     {
                        recv_len = recvfrom(0,data_buf,remained_rsr,0,0);
                        remained_rsr -= (recv_len+2+4); // length of DATA packet size - 2bytes, length of CRC - 4 bytes
                        if(remained_rsr < 0)
{
                           // Error. It maybe receive an un-acceptable MACRAW data and should be ignored that.
                           break;
                        }
                        process_macraw_data(data_buf,recv_len);
                     }
                  }
                  else                                 // Normal
                  {
                     recv_len = recvfrom(0,data_buf,remained_rsr,0,0);
                     process_macraw_data(data_buf,recv_len);
                  }
               }
               break;
            case SOCK_CLOSED:
               socket(0,Sn_MR_MACRAW,0x1000,Sn_MR_MF); // open or re-open the MACRAW SOCKET with MAC filter flag.
               break;
         } // end switch
      } // end while
   } // end main
Definition at line 342 of file socket.c.
References IINCHIP_READ(), MR, MR_FS, setSn_CR(), Sn_CR_RECV, Sn_MR, Sn_MR_IPRAW, Sn_MR_MACRAW, Sn_MR_UDP, and wiz_read_buf().
Referenced by loopback_udp().
uint32 send (SOCKET s, uint8 * buf, uint32 len)
It sends TCP data on a connection SOCKET.
It is used to write outgoing data on a connection SOCKET.
It is valid only in TCP mode.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] buf A buffer containing the data to be transmitted
[in] len The byte length of the data in buf
Returns:
If no error occurs, it returns the total number of bytes sent, which can be less than the number indicated by len when len is greater than the allocated size of internal TX memory.
If error such as timeout and abnormally disconnect occurs, it returns 0.
Remarks:
It is a blocking function which doesn't return until len lenght data is transmitted completely.
Note:
if you want to use non blocking function, "do{...}while(freesize < ret)" code block can be replaced with the below code.
 while((freesize = getSn_TX_FSR(s))==0); It can tranmit data as many as free size
       ret = freesize;
Definition at line 133 of file socket.c.
References check_sendok_flag, getIINCHIP_TxMAX(), getSn_IR(), getSn_SSR(), getSn_TX_FSR(), MR, setSn_CR(), setSn_IR(), setSn_TX_WRSR(), Sn_CR_SEND, Sn_IR_SENDOK, SOCK_CLOSE_WAIT, SOCK_CLOSED, SOCK_ESTABLISHED, and wiz_write_buf().
Referenced by loopback_tcpc(), and loopback_tcps().
uint32 sendto (SOCKET s, uint8 * buf, uint32 len, uint8 * addr, uint16 port)
It sends UDP, IPRAW, or MACRAW data.
It is normally used on a connectionless SOCKET to send a datagram to a specific peer identified by the to parameter(addr, port). Even if the connectionless SOCKET has been previously connected to a specific address, the addr and port parameters override the destination address for that particular datagram only.
On the IPRAW SOCKET, the port parameter are ignored.
On the MACRAW SOCKET, the addr and port parameters are ignored, making sendto() equivalent to send(). But, The destination and source information must be included in front of buf.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] buf A buffer containing the data to be transmitted
[in] len The byte length of the data in buf
[in] addr An optional pointer to the address of destination.
[in] port An optional the port number of destination.
Returns:
If no error occurs, it returns the total number of bytes sent, which can be less than the number indicated by len when len is greater than the allocated size of internal TX memory.
If error such as ARP timeout and abnormally close occurs, it returns 0.
Remarks:
It is a blocking function which doesn't return until Sn_IR_SENDOK becomes '1'. It should wait in order to prevent from overriding the destination information.
Warning:
Warning:
If sendto() is failed by ARP timeout, Sn_TX_FSR is decreased as size of the transmitted data. If ARP timeout occurs continuously, Sn_RX_FSR maybe become 0 and any data can't be transmitted. But, don't worry about that. If sendto() successes only once, Sn_RX_FSR is perfectly recovered.
Definition at line 284 of file socket.c.
References getIINCHIP_TxMAX(), getSn_IR(), getSn_SSR(), IINCHIP_WRITE(), setSn_CR(), setSn_IR(), setSn_TX_WRSR(), Sn_CR_SEND, Sn_DIPR, Sn_DPORTR, Sn_IR_SENDOK, Sn_IR_TIMEOUT, SOCK_CLOSED, and wiz_write_buf().
Referenced by close(), and loopback_udp().
uint8 socket (SOCKET s, uint8 protocol, uint16 port, uint16 flag)
Open a SOCKET.
It opens a SOCKET according protocol and bind the SOCKET with port number.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] protocol SOCKET protocol such as TCP, UDP and IP.
Refer to Sn_MR_TCP, Sn_MR_UDP, Sn_MR_IPRAW, Sn_MR_MACRAW and Sn_MR_PPPoE.
[in] port port number to be binded
[in] flag SOCKET option such as alignment, no-delayed ack, and etc.
Refer to Sn_MR_ALIGN, Sn_MR_MULTI, Sn_MR_MF and Sn_MR_ND/Sn_MR_IGMPv.
Returns:
Always, It returns 1.
Definition at line 38 of file socket.c.
References check_sendok_flag, getSn_SSR(), IINCHIP_READ(), iinchip_source_port, IINCHIP_WRITE(), setSn_CR(), Sn_CR_OPEN, Sn_MR, and Sn_PORTR.
Referenced by close(), loopback_tcpc(), loopback_tcps(), and loopback_udp().