W5300 - SOCKET APIs: include/w5300.h File Reference
include/w5300.h File Reference
Detailed Description
Definition register of W5300 and basic I/O functions.
This file defines the memory map and values of W5300 register.
Also, it defines the basic I/O function to access register of W5300.
Author:
MidnightCow
Date:
08/08/2008
Version:
1.2.0
Revision History :
Date Version Author Description
24/03/2008 1.0.0 MidnightCow Release with W5300 launching
01/05/2008 1.0.1 MidnightCow Refer to M_01052008.
Modify a logical error in iinchip_irq().
15/05/2008 1.1.0 MidnightCow Refer to M_15052008.
Delete 'getSn_DPORTR()' because Sn_DPORTR is write-only register.
Replace Sn_DHAR2 with Sn_DIPR2 in getSn_DIPR().
08/08/2008 1.2.0 MidnightCow - Refer to M_08082008.
Add IINCHIP_CRITICAL_SECTION_ENTER() & IINCHIP_CRITICAL_SECTION_EXIT() to wiz_read_buf() and wiz_write_buf().
- Add the description to Sn_PROTOR with IPPROTO_XXX definition.
- Modify the description of Sn_SSR and close().
Definition in file w5300.h.
#include "iinchip_conf.h"
#include "types.h"
Defines
#define MR (__DEF_IINCHIP_MAP_BASE__)
Mode register.
#define IDM_AR (__DEF_IINCHIP_MAP_BASE__ + 0x02)
Indirect mode address register.
#define IDM_DR (__DEF_IINCHIP_MAP_BASE__ + 0x04)
Indirect mode data register.
#define IR (COMMON_REG_BASE + 0x02)
Interrupt register.
#define IMR (COMMON_REG_BASE + 0x04)
Interrupt mask register.
#define SHAR (COMMON_REG_BASE + 0x08)
Source hardware address register.
#define GAR (COMMON_REG_BASE + 0x10)
Gateway IP address register.
#define SUBR (COMMON_REG_BASE + 0x14)
Subnet mask register.
#define SIPR (COMMON_REG_BASE + 0x18)
Source IP address register.
#define RTR (COMMON_REG_BASE + 0x1C)
Retransmittion timeout-period register.
#define RCR (COMMON_REG_BASE + 0x1E)
Retransmittion retry count reigster.
#define TMS01R (COMMON_REG_BASE + 0x20)
Transmit memory size of each SOCKET reigster.
#define TMS23R (TMS01R + 2)
#define TMS45R (TMS01R + 4)
#define TMS67R (TMS01R + 6)
#define RMS01R (COMMON_REG_BASE + 0x28)
Transmit memory size of each SOCKET reigster.
#define RMS23R (RMS01R + 2)
#define RMS45R (RMS01R + 4)
#define RMS67R (RMS01R + 6)
#define MTYPER (COMMON_REG_BASE + 0x30)
Memory type register.
#define PATR (COMMON_REG_BASE + 0x32)
Authentication type register.
#define PTIMER (COMMON_REG_BASE + 0x36)
PPP link control protocol request timer register.
#define PMAGICR (COMMON_REG_BASE + 0x38)
PPP LCP magic number register.
#define PSIDR (COMMON_REG_BASE + 0x3C)
PPPoE session ID register.
#define PDHAR (COMMON_REG_BASE + 0x40)
PPPoE destination hardware address register.
#define UIPR (COMMON_REG_BASE + 0x48)
Unreachable IP address register.
#define UPORTR (COMMON_REG_BASE + 0x4C)
Unreachable port number register.
#define FMTUR (COMMON_REG_BASE + 0x4E)
Fragment MTU register.
#define Pn_BRDYR(n) (COMMON_REG_BASE + 0x60 + n*4)
PIN 'BRDYn' configure register.
#define Pn_BDPTHR(n) (COMMON_REG_BASE + 0x60 + n*4 + 2)
PIN 'BRDYn' buffer depth Register.
#define IDR (COMMON_REG_BASE + 0xFE)
W5300 identification register
#define Sn_MR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x00)
SOCKETn mode register
#define Sn_CR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x02)
SOCKETn command register
#define Sn_IMR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x04)
SOCKETn interrupt mask register
#define Sn_IR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x06)
SOCKETn interrupt register
#define Sn_SSR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x08)
SOCKETn status register
#define Sn_PORTR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x0A)
SOCKETn source port register
#define Sn_DHAR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x0C)
SOCKETn destination hardware address register
#define Sn_DPORTR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x12)
SOCKETn destination port register
#define Sn_DIPR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x14)
SOCKETn destination IP address register
#define Sn_MSSR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x18)
SOCKETn maximum segment size register
#define Sn_PROTOR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x1A)
SOCKETn protocol of IP header field register
#define Sn_KPALVTR(n) Sn_PROTOR(n)
SOCKETn keep alive timer register
#define Sn_TOSR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x1C)
SOCKETn IP type of service(TOS) register
#define Sn_TTLR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x1E)
SOCKETn IP time to live(TTL) register
#define Sn_TX_WRSR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x20)
SOCKETn TX write size register
#define Sn_TX_FSR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x0024)
SOCKETn TX free size register
#define Sn_RX_RSR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x0028)
SOCKETn RX received size register
#define Sn_FRAGR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x002C)
SOCKETn fragment register
#define Sn_TX_FIFOR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x2E)
SOCKETn TX FIFO register
#define Sn_RX_FIFOR(n) (SOCKET_REG_BASE + n * SOCKET_REG_SIZE + 0x30)
SOCKET n RX FIFO register
#define MR_DBW (1 << 15)
Data bus width bit of MR.
#define MR_MPF (1 << 14)
Mac layer pause frame bit of MR.
#define MR_WDF(X) ((X & 0x07) << 11)
Write data fetch time bit of MR.
#define MR_RDH (1 << 10)
Read data hold time bit of MR.
#define MR_FS (1 << 8)
FIFO swap bit of MR.
#define MR_RST (1 << 7)
S/W reset bit of MR.
#define MR_MT (1 << 5)
Memory test bit of MR.
#define MR_PB (1 << 4)
Ping block bit of MR.
#define MR_PPPoE (1 << 3)
PPPoE bit of MR.
#define MR_DBS (1 << 2)
Data bus swap of MR.
#define MR_IND (1 << 0)
Indirect mode bit of MR.
#define IR_IPCF (1 << 7)
IP conflict bit of IR.
#define IR_DPUR (1 << 6)
Destination port unreachable bit of IR.
#define IR_PPPT (1 << 5)
PPPoE terminate bit of IR.
#define IR_FMTU (1 << 4)
Fragment MTU bit of IR.
#define IR_SnINT(n) (0x01 << n)
SOCKETn interrupt occurrence bit of IR.
#define Pn_PEN (1 << 7)
PIN 'BRDYn' enable bit of Pn_BRDYR.
#define Pn_MT (1 << 6)
PIN memory type bit of Pn_BRDYR.
#define Pn_PPL (1 << 5)
PIN Polarity bit of Pn_BRDYR.
#define Pn_SN(n) ((n & 0x07) << 0)
PIN Polarity bit of Pn_BRDYR.
#define Sn_MR_ALIGN (1 << 8)
Alignment bit of Sn_MR.
#define Sn_MR_MULTI (1 << 7)
Multicasting bit of Sn_MR.
#define Sn_MR_MF (1 << 6)
MAC filter bit of Sn_MR.
#define Sn_MR_IGMPv (1 << 5)
IGMP version bit of Sn_MR.
#define Sn_MR_ND (1 << 5)
No delayed ack bit of Sn_MR.
#define Sn_MR_CLOSE 0x00
Protocol bits of Sn_MR.
#define Sn_MR_TCP 0x01
Protocol bits of Sn_MR.
#define Sn_MR_UDP 0x02
Protocol bits of Sn_MR.
#define Sn_MR_IPRAW 0x03
Protocol bits of Sn_MR.
#define Sn_MR_MACRAW 0x04
Protocol bits of Sn_MR.
#define Sn_MR_PPPoE 0x05
Protocol bits of Sn_MR.
#define Sn_CR_OPEN 0x01
OPEN command value of Sn_CR.
#define Sn_CR_LISTEN 0x02
LISTEN command value of Sn_CR.
#define Sn_CR_CONNECT 0x04
CONNECT command value of Sn_CR.
#define Sn_CR_DISCON 0x08
DISCONNECT command value of Sn_CR.
#define Sn_CR_CLOSE 0x10
CLOSE command value of Sn_CR.
#define Sn_CR_SEND 0x20
SEND command value of Sn_CR.
#define Sn_CR_SEND_MAC 0x21
SEND_MAC command value of Sn_CR.
#define Sn_CR_SEND_KEEP 0x22
SEND_KEEP command value of Sn_CR.
#define Sn_CR_RECV 0x40
RECV command value of Sn_CR.
#define Sn_CR_PCON 0x23
PCON command value of Sn_CR.
#define Sn_CR_PDISCON 0x24
PDISCON command value of Sn_CR.
#define Sn_CR_PCR 0x25
PCR command value of Sn_CR.
#define Sn_CR_PCN 0x26
PCN command value of Sn_CR.
#define Sn_CR_PCJ 0x27
PCJ command value of Sn_CR.
#define Sn_IR_PRECV 0x80
PPP receive bit of Sn_IR.
#define Sn_IR_PFAIL 0x40
PPP fail bit of Sn_IR.
#define Sn_IR_PNEXT 0x20
PPP next phase bit of Sn_IR.
#define Sn_IR_SENDOK 0x10
Send OK bit of Sn_IR.
#define Sn_IR_TIMEOUT 0x08
Timout bit of Sn_IR.
#define Sn_IR_RECV 0x04
Receive bit of Sn_IR.
#define Sn_IR_DISCON 0x02
Disconnect bit of Sn_IR.
#define Sn_IR_CON 0x01
Connect bit of Sn_IR.
#define SOCK_CLOSED 0x00
It is the status that resource of SOCKETn is released.
#define SOCK_ARP 0x01
It is the status that ARP-request is transmitted in order to acquire destination hardware address.
#define SOCK_INIT 0x13
It is the status that SOCKETn is open as TCP mode.
#define SOCK_LISTEN 0x14
It is the status that SOCKETn operates as "TCP SERVER" and waits for connection-request (SYN packet) from "TCP CLIENT".
#define SOCK_SYNSENT 0x15
It is the status that connect-request(SYN packet) is transmitted to "TCP SERVER".
#define SOCK_SYNRECV 0x16
It is the status that connect-request(SYN packet) is received from "TCP CLIENT".
#define SOCK_ESTABLISHED 0x17
It is the status that TCP connection is established.
#define SOCK_FIN_WAIT 0x18
It is the status that SOCKETn is closed.
#define SOCK_CLOSING 0x1A
It is the status that SOCKETn is closed.
#define SOCK_TIME_WAIT 0x1B
It is the status that SOCKETn is closed.
#define SOCK_CLOSE_WAIT 0x1C
It is the status that disconnect-request(FIN packet) is received from the peer.
#define SOCK_LAST_ACK 0x1D
It is the status that SOCKETn is closed.
#define SOCK_UDP 0x22
It is the status that SOCKETn is open as UDP mode.
#define SOCK_IPRAW 0x32
It is the status that SOCKETn is open as IPRAW mode.
#define SOCK_MACRAW 0x42
It is the status that SOCKET0 is open as MACRAW mode.
#define SOCK_PPPoE 0x5F
It is the status that SOCKET0 is open as PPPoE mode.
#define IPPROTO_IP 0
#define IPPROTO_ICMP 1
#define IPPROTO_IGMP 2
#define IPPROTO_GGP 3
#define IPPROTO_TCP 6
#define IPPROTO_PUP 12
#define IPPROTO_UDP 17
#define IPPROTO_IDP 22
#define IPPROTO_ND 77
#define IPPROTO_RAW 255
Functions
uint16 IINCHIP_READ (uint32 addr)
Basic I/O function.
void IINCHIP_WRITE (uint32 addr, uint16 data)
Basic I/O function.
uint16 getMR (void)
It gets MR value.
void setMR (uint16 val)
It sets MR value.
uint16 getIR (void)
It gets IR value.
void setIR (uint16 val)
It sets IR value.
uint16 getIMR (void)
It gets IMR value.
void setIMR (uint16 mask)
It sets IMR value.
void getSHAR (uint8 *addr)
It gets the source hardware address.
void setSHAR (uint8 *addr)
It sets the source hardware address.
void getGAR (uint8 *addr)
It gets the gateway IP address.
void setGAR (uint8 *addr)
It sets the gateway IP address.
void getSUBR (uint8 *addr)
It gets the subnet mask address.
void setSUBR (uint8 *addr)
It sets the subnet mask address.
void getSIPR (uint8 *addr)
It gets the source IP address.
void setSIPR (uint8 *addr)
It sets the source IP address.
uint16 getRTR (void)
It gets RTR value.
void setRTR (uint16 timeout)
It sets RTR value.
uint8 getRCR (void)
It gets RCR value.
void setRCR (uint8 retry)
It sets RCR value.
uint16 getPATR (void)
It gets PATR value.
uint8 getPTIMER (void)
It gets PTIMER value.
void setPTIMER (uint8 time)
It sets PTIMER value.
uint8 getPMAGICR (void)
It gets PMAGICR value.
void setPMAGICR (uint8 magic)
It sets PTIMER value.
uint16 getPSIDR (void)
It gets PSIDR value.
void getPDHAR (uint8 *addr)
It gets the PPPoE server hardware address.
void getUIPR (uint8 *addr)
It gets the unreachable destination IP address of ICMP message.
uint16 getUPORTR (void)
It gets the unreachable destination port number of ICMP message.
uint16 getFMTUR (void)
It gets the fragmented MTU value of ICMP message.
uint8 getPn_BRDYR (uint8 p)
It gets Pn_BRDYR value.
void setPn_BRDYR (uint8 p, uint8 cfg)
It sets Pn_BRDYR value.
uint16 getPn_BDPTHR (uint8 p)
It gets the buffer depth of PIN "BRDYn".
void setPn_BDPTHR (uint8 p, uint16 depth)
It sets the buffer depth of PIN "BRDYn".
uint16 getIDR (void)
It gets the ID of W5300.
uint16 getSn_MR (SOCKET s)
It gets Sn_MR value.
void setSn_MR (SOCKET s, uint16 mode)
It sets Sn_MR value.
uint8 getSn_CR (SOCKET s)
It gets Sn_CR value.
void setSn_CR (SOCKET s, uint16 com)
It sets Sn_CR value.
uint8 getSn_IMR (SOCKET s)
It gets Sn_IMR value.
void setSn_IMR (SOCKET s, uint8 mask)
It sets Sn_IMR value.
uint8 getSn_IR (SOCKET s)
It gets Sn_IR value.
void setSn_IR (SOCKET s, uint8 ir)
It sets Sn_IR value.
uint8 getSn_SSR (SOCKET s)
It gets Sn_SSR value.
void getSn_DHAR (SOCKET s, uint8 *addr)
It gets Sn_DHAR value.
void setSn_DHAR (SOCKET s, uint8 *addr)
It sets Sn_DHAR value.
void setSn_DPORTR (SOCKET s, uint16 port)
It sets Sn_DPORTR value.
void getSn_DIPR (SOCKET s, uint8 *addr)
It gets Sn_DIPR value.
void setSn_DIPR (SOCKET s, uint8 *addr)
It sets Sn_DIPR value.
uint16 getSn_MSSR (SOCKET s)
It gets Sn_MSSR value.
void setSn_MSSR (SOCKET s, uint16 mss)
It sets Sn_MSSR value.
uint8 getSn_KPALVTR (SOCKET s)
It gets Sn_KPALVTR value.
void setSn_KPALVTR (SOCKET s, uint8 time)
It sets Sn_KPALVTR value.
uint32 getSn_TX_WRSR (SOCKET s)
It gets Sn_TX_WRSR value.
void setSn_TX_WRSR (SOCKET s, uint32 size)
It gets Sn_KPALVTR value.
uint32 getSn_TX_FSR (SOCKET s)
It gets Sn_TX_FSR value.
uint32 getSn_RX_RSR (SOCKET s)
It gets Sn_RX_RSR value.
void setSn_TX_FIFOR (SOCKET s, uint16 data)
It sets Sn_TX_FIFOR value.
uint16 getSn_RX_FIFOR (SOCKET s)
It gets Sn_RX_FIFOR value.
uint8 getSn_PROTOR (SOCKET s)
It gets Sn_PROTOR value.
void setSn_PROTOR (SOCKET s, uint8 pronum)
It sets Sn_PROTOR value.
uint8 getSn_TOSR (SOCKET s)
It gets Sn_TOSR value.
void setSn_TOSR (SOCKET s, uint8 tos)
It sets Sn_TOSR value.
uint8 getSn_TTLR (SOCKET s)
It gets Sn_TTLR value.
void setSn_TTLR (SOCKET s, uint8 ttl)
It sets Sn_TTLR value.
uint8 getSn_FRAGR (SOCKET s)
It gets Sn_FRAGR value.
void setSn_FRAGR (SOCKET s, uint8 frag)
It sets Sn_FRAGR value.
void iinchip_init (void)
It initializes W5300.
void iinchip_irq (void)
It handles the interrupt of W5300.
uint8 sysinit (uint8 *tx_size, uint8 *rx_size)
It allocate internal TX/RX memory of each SOCKET.
uint32 wiz_write_buf (SOCKET s, uint8 *buf, uint32 len)
It copies data to interna1 TX memory.
uint32 wiz_read_buf (SOCKET s, uint8 *buf, uint32 len)
It copies data to your buffer from internal RX memory.
uint32 getIINCHIP_TxMAX (SOCKET s)
It gets the max size of internal TX memory of each SOCKET.
uint32 getIINCHIP_RxMAX (SOCKET s)
It gets the max size of internal RX memory of each SOCKET.
uint8 pppinit (uint8 *id, uint8 idlen, uint8 *passwd, uint8 passwdlen)
It initializes to PPPoE of W5300.
void pppterm (uint8 *mac, uint16 sessionid)
It terminates PPPoE connection.
void wait_1us (uint32 us)
Delay function Refer to wait_10ms().
void wait_1ms (uint32 ms)
Delay function Refer to wait_10ms().
void wait_10ms (uint32 ms)
Delay function.
Define Documentation
#define IPPROTO_GGP 3
Gateway-to-Gateway (deprecated)
Definition at line 1756 of file w5300.h.
#define IPPROTO_ICMP 1
Control message protocol
Definition at line 1754 of file w5300.h.
#define IPPROTO_IDP 22
XNS idp
Definition at line 1760 of file w5300.h.
#define IPPROTO_IGMP 2
Internet group management protocol
Definition at line 1755 of file w5300.h.
#define IPPROTO_IP 0
Dummy for IP
Definition at line 1753 of file w5300.h.
#define IPPROTO_ND 77
UNOFFICIAL net disk protocol
Definition at line 1761 of file w5300.h.
#define IPPROTO_PUP 12
PUP
Definition at line 1758 of file w5300.h.
#define IPPROTO_RAW 255
Raw IP packet
Definition at line 1762 of file w5300.h.
#define IPPROTO_TCP 6
TCP
Definition at line 1757 of file w5300.h.
#define IPPROTO_UDP 17
UDP
Definition at line 1759 of file w5300.h.
#define IR_DPUR (1 << 6)
Destination port unreachable bit of IR.
It's set as '1' when receiving ICMP(destination port unreachable) packet.
See also:
UIPR, UPORTR
Definition at line 1134 of file w5300.h.
Referenced by iinchip_irq().
#define IR_FMTU (1 << 4)
Fragment MTU bit of IR.
When receiving ICMP (Fragment MTU) packet, it's set as '1'.
See also:
FMTUR
Definition at line 1147 of file w5300.h.
#define IR_IPCF (1 << 7)
IP conflict bit of IR.
It's set as '1' when receiving ARP-request packet having same IP address as SIPR of W5300.
Definition at line 1127 of file w5300.h.
Referenced by iinchip_irq().
#define IR_PPPT (1 << 5)
PPPoE terminate bit of IR.
When the connection with server is closed at the PPPoE mode, it is set as '1'.
Definition at line 1140 of file w5300.h.
#define IR_SnINT (n) (0x01 << n)
SOCKETn interrupt occurrence bit of IR.
When an interrupt occurs at the SOCKETn, it becomes '1'. This interrupt information is applied to Sn_IR's LSB.
This Bit is automatically cleared when Sn_IR's LSB is cleared to 0x00 by Host.
See also:
Sn_IR
Definition at line 1155 of file w5300.h.
Referenced by iinchip_irq().
#define MR_DBS (1 << 2)
Data bus swap of MR.
0 : Diable swap
1 : Enable swap
This bit swaps MSB and LSB of all registers including Sn_TX_FIFOR/ Sn_RX_FIFOR.
Note:
This bit can be applied when MR_DBW is '1' .
Definition at line 1106 of file w5300.h.
#define MR_DBW (1 << 15)
Data bus width bit of MR.
0 : 8 bit
1 : 16 bit
Read only. When reset of W5300, it is fixed according to logic level of PIN 'BIT16EN'.
Definition at line 1024 of file w5300.h.
#define MR_FS (1 << 8)
FIFO swap bit of MR.
0 : Diable swap
1 : Enable swap
It swaps the most significant byte (MSB) and least significant byte (LSB) of Sn_TX_FIFOR & Sn_RX_FIFOR.
Basically, the byte ordering of W5300 is big-endian.
Definition at line 1061 of file w5300.h.
Referenced by pppinit(), recv(), and recvfrom().
#define MR_IND (1 << 0)
Indirect mode bit of MR.
0 : Direct Address Mode
1 : Indirect Address Mode
It sets host interface mode of W5300.
See also:
__DEF_IINCHIP_ADDRESS_MODE__
Definition at line 1116 of file w5300.h.
Referenced by iinchip_init().
#define MR_MPF (1 << 14)
Mac layer pause frame bit of MR.
Read only. It is set as '1', when pause frame is received from router or switch.
When set as '1', all data is paused until changing to '0'.
Definition at line 1032 of file w5300.h.
#define MR_MT (1 << 5)
Memory test bit of MR.
0 : Disable Internal TX/RX Memory Test
1 : Enable Internal TX/RX Memory Test
For the detail, refer to "How to test internal TX/RX memory.pdf".
Definition at line 1078 of file w5300.h.
#define MR_PB (1 << 4)
Ping block bit of MR.
0 : Disable ping block
1 : Enable ping block
Definition at line 1086 of file w5300.h.
#define MR_PPPoE (1 << 3)
PPPoE bit of MR.
0 : Disable PPPoE mode
1 : Enable PPPoE mode
This bit should be set as '1', when connecting to ADSL server with router or others.
For the detail, refer to "How to use PPPoE in W5300.pdf"
Definition at line 1096 of file w5300.h.
Referenced by pppinit(), and pppterm().
#define MR_RDH (1 << 10)
Read data hold time bit of MR.
0 : No use
1 : Use
When the Host reads, W5300 holds the Read Data during '2' X 'PLL_CLK' after the read operation is finished ('/CS' is de-asserted as High).
Definition at line 1050 of file w5300.h.
#define MR_RST (1 << 7)
S/W reset bit of MR.
If it's set as '1', W5300 is reset. This Bit is automatically cleared after reset.
Definition at line 1069 of file w5300.h.
Referenced by iinchip_init().
#define MR_WDF (X) ((X & 0x07) << 11)
Write data fetch time bit of MR.
When the host writes, since '/CS' is asserted low, W5300 fetches Write Data after 'X' X 'PLL_CLK'.
Definition at line 1040 of file w5300.h.
#define Pn_MT (1 << 6)
PIN memory type bit of Pn_BRDYR.
'0' - RX memory
'1' - TX memory
It sets the type of socket memory to monitor.
Definition at line 1177 of file w5300.h.
#define Pn_PEN (1 << 7)
PIN 'BRDYn' enable bit of Pn_BRDYR.
'0' - Disable PIN 'BRDYn'
'1' - Enable PIN 'BRDYn'
When using PIN "BRDYn", set it as "1".
Definition at line 1168 of file w5300.h.
#define Pn_PPL (1 << 5)
PIN Polarity bit of Pn_BRDYR.
'0' - Low sensitive
'1' - High sensitive
When Free/Received buffer size of the specified SOCKET's TX/RX memory is same or bigger than Pn_DPTHR, set the logic level of PIN 'BRDYn' to be signaled to the Host.
See also:
Pn_BDPTHR
Definition at line 1187 of file w5300.h.
#define Pn_SN (n) ((n & 0x07) << 0)
PIN Polarity bit of Pn_BRDYR.
Set the SOCKET number to monitor through PIN 'BRDYn'.
0 <= n <= MAX_SOCK_NUM.
Definition at line 1195 of file w5300.h.
#define RMS23R (RMS01R + 2)
Refer to RMS01R.
Definition at line 322 of file w5300.h.
Referenced by sysinit().
#define RMS45R (RMS01R + 4)
Refer to RMS01R.
Definition at line 323 of file w5300.h.
Referenced by sysinit().
#define RMS67R (RMS01R + 6)
Refer to RMS01R.
Definition at line 324 of file w5300.h.
Referenced by sysinit().
#define Sn_CR_CLOSE 0x10
CLOSE command value of Sn_CR.
It closes SOCKETn regardless of Sn_SSR 's value. Sn_SSR is changed to SOCK_CLOSED.
Definition at line 1392 of file w5300.h.
Referenced by close(), pppinit(), and pppterm().
#define Sn_CR_CONNECT 0x04
CONNECT command value of Sn_CR.
It is valid only when Sn_MR(P3:P0) = Sn_MR_TCP and operates SOCKETn as 'TCP-CLIENT'.
It transmits connect-request(SYN packet) to the TCP server designated with Sn_DIPR and Sn_DPORTR.
When connect-request is successfully processed (when receiving SYN/ACK packet), Sn_IR(Sn_IR_CON) becomes '1', and Sn_SSR is changed to SOCK_ESTABLISHED.
There are 3 cases if connect-request is failed.
when ARP timeout occurs (Sn_IR(Sn_IR_TIMEOUT)='1') because destination hardware address is not acquired through ARP process
when SYN/ACK packet is not received and TCP timout occurrs (Sn_IR(Sn_IR_TIMEOUT)='1').
When RST packet is received instead of SYN/ACK packet.
In above 3 cases, Sn_SSR is changed to SOCK_CLOSED.
Definition at line 1351 of file w5300.h.
Referenced by connect().
#define Sn_CR_DISCON 0x08
DISCONNECT command value of Sn_CR.
It is valid only when Sn_MR(P3:P0) = Sn_MR_TCP and operates SOCKETn as both 'TCP-SERVER' and 'TCP-CLIENT'.
It performs Disconnect-process.
Active close : It transmits disconnect-request(FIN packet) to the connected peer.
Passive close : When receiving disconnect-request (FIN packet) from the peer, it transmits FIN packet.
If Disconnect-request is successful (when receiving FIN/ACK packet), Sn_SSR is changed to SOCK_CLOSED. If Disconnect-request is failed, TCP timeout occurs(Sn_IR(Sn_IR_TIMEOUT)='1') and Sn_SSR is changed to SOCK_CLOSED.
Note:
If Sn_CR_CLOSE is used instead of Sn_CR_DISCON, only Sn_SSR is changed to SOCK_CLOSED without disconnect-process (disconnect-request).
If RST packet is received from the peer during communication, Sn_SSR is unconditionally changed to SOCK_CLOSED.
Definition at line 1371 of file w5300.h.
Referenced by disconnect().
#define Sn_CR_LISTEN 0x02
LISTEN command value of Sn_CR.
It is valid only when Sn_MR(P3:P0) = Sn_MR_TCP and operates SOCKETn as 'TCP-SERVER'.
It changes Sn_SSR to SOCK_LISTEN at the SOCK_INIT in order to wait for connect-request (SYN packet) from any 'TCP Clinet'.
When Sn_SSR is SOCK_LISTEN and connect-request from a TCP Client is successfully processed, Sn_IR(Sn_IR_CON) becomes '1' and Sn_SSR is changed to SOCK_ESTABLISHED.
In case that the connect-request is not processed (SYN/ACK transmission is failed), TCP timeout occurs (Sn_IR(Sn_IR_TIMEOUT)='1') and Sn_SSR is changed to SOCK_CLOSED.
Note:
If TCP connect-request port number of TCP Client does not exist, W5300 transmits RST packet and Sn_SSR is not changed.
Definition at line 1332 of file w5300.h.
Referenced by listen().
#define Sn_CR_OPEN 0x01
OPEN command value of Sn_CR.
It initializes SOCKETn and opens according to protocol type set in Sn_MR(P3:P0).
Below is the value change of Sn_SSR according to Sn_MR(P3:P0).
Sn_MR_CLOSE : Not available
Sn_MR_TCP : SOCK_INIT
Sn_MR_UDP : SOCK_UDP
Sn_MR_IPRAW : SOCK_IPRAW
Sn_MR_MAC : SOCK_MACRAW
Sn_MR_PPPoE : SOCK_PPPoE
Definition at line 1318 of file w5300.h.
Referenced by pppinit(), pppterm(), and socket().
#define Sn_CR_PCJ 0x27
PCJ command value of Sn_CR.
It is valid only in Sn_MR(P3:P0) = Sn_MR_PPPoE.
In each phase, it transmits REJECT message. Refer to "How to use PPPoE in W5300.pdf"
Definition at line 1504 of file w5300.h.
Referenced by pppinit_in().
#define Sn_CR_PCN 0x26
PCN command value of Sn_CR.
It is valid only in Sn_MR(P3:P0) = Sn_MR_PPPoE.
In each phase, it transmits NAK message. Refer to "How to use PPPoE in W5300.pdf"
Definition at line 1495 of file w5300.h.
#define Sn_CR_PCON 0x23
PCON command value of Sn_CR.
It is valid only in Sn_MR(P3:P0) = Sn_MR_PPPoE.
PPPoE connection begins by transmitting PPPoE discovery packet.
Refer to "How to use PPPoE in W5300.pdf"
Definition at line 1468 of file w5300.h.
Referenced by pppinit_in().
#define Sn_CR_PCR 0x25
PCR command value of Sn_CR.
It is valid only in Sn_MR(P3:P0) = Sn_MR_PPPoE.
In each phase, it transmits REQ message. Refer to "How to use PPPoE in W5300.pdf"
Definition at line 1486 of file w5300.h.
Referenced by pppinit_in().
#define Sn_CR_PDISCON 0x24
PDISCON command value of Sn_CR.
It is valid only in Sn_MR(P3:P0) = Sn_MR_PPPoE.
Closes PPPoE connection. Refer to "How to use PPPoE in W5300.pdf"
Definition at line 1477 of file w5300.h.
Referenced by pppterm().
#define Sn_CR_RECV 0x40
RECV command value of Sn_CR.
It notifies that the host received the data packet of SOCKETn.
Note:
Before RECV command, the host should copy receiving data packet from internal RX memory into the host memory through Sn_RX_FIFOR.
Definition at line 1458 of file w5300.h.
Referenced by pppinit_in(), recv(), and recvfrom().
#define Sn_CR_SEND 0x20
SEND command value of Sn_CR.
It transmits data (DATA packets) as big as the size of Sn_TX_WRSR. In case that Sn_MR(P3:P0) is Sn_MR_TCP or Sn_MR_UDP, if Sn_TX_WRSR of data is bigger than maximum segment size(MSS), W5300 automatically divides data in MSS unit, and transmits the divided data.
In case that Sn_MR(P3:P0) is Sn_MR_IPRAW or Sn_MR_MACRAW, this function is not supported. Host should divide data in MSS unit and transmit the divided data to a peer.
When completing the Sn_CR_SEND process, Sn_IR(Sn_IR_SENDOK) becomes '1'. After checking Sn_IR(Sn_IR_SENDOK) = '1', Host can perform Sn_CR_SEND for the next data transmittion.
If data is successfully transmitted to the peer by Sn_CR_SEND (when DATA/ACK packet is received from the peer), Sn_TX_FSR is increased by the size of transmitted data. If not (when DATA/ACK packet is not received), TCP timeout occurs (Sn_IR(Sn_IR_TIMEOUT)='1') and Sn_SSR is changed to SOCK_CLOSED.
Note:
Host copies TX data into internal TX memory of SOCKETn through Sn_TX_FIFOR before performing Sn_CR_SEND, and configures data size in Sn_TX_WRSR.
Definition at line 1400 of file w5300.h.
Referenced by recv(), send(), and sendto().
#define Sn_CR_SEND_KEEP 0x22
SEND_KEEP command value of Sn_CR.
It is valid only when Sn_MR(P3:P0) = Sn_MR_TCP.
In order to check TCP connection status with the peer, KEEP ALIVE(KA) packet can be transmitted. Sn_CR_SEND_KEEP is available only in case of Sn_KPALVTR = 0, but ignored in case of Sn_KPALVTR > 0.
In case of Sn_KPALVTR > 0, KA packet is automatically transmitted if there is no data communication during the time of Sn_KPALVTR.
If KA packet is successfully transmitted (when KA/ACK packet is received from the peer), Sn_SSR maintains SOCK_ESTABLISHED status. If it is failed to transmit the KA packet (when the peer already closed the connection, or KA/ACK is not transmitted), TCP timeout will occurs(Sn_IR(Sn_IR_TIMEOUT)='1') and Sn_SSR is changed to SOCK_CLOSED.
Note:
KA packet can be transmitted after one or more data communication is processed.
Definition at line 1438 of file w5300.h.
#define Sn_CR_SEND_MAC 0x21
SEND_MAC command value of Sn_CR.
It is valid only in Sn_MR(P3:P0) = Sn_MR_UDP or Sn_MR_IPRAW
The basic operation is same as Sn_CR_SEND.
Sn_CR_SEND needs ARP process that acquires destination hardware address, but Sn_CR_SEND_MAC is no need ARP process and just use the user-specified destination hardware address in Sn_DHAR. Sn_CR_SEND_MAC can reduce network traffic by removing ARP process when sending UDP/IP data to the destination.
Definition at line 1425 of file w5300.h.
#define Sn_IR_CON 0x01
Connect bit of Sn_IR.
Setting for the case that the connection with the peer is successfully established.
Definition at line 1569 of file w5300.h.
Referenced by loopback_tcpc(), and loopback_tcps().
#define Sn_IR_DISCON 0x02
Disconnect bit of Sn_IR.
Setting for the case that FIN or FIN/ACK packet is received from the peer
Definition at line 1562 of file w5300.h.
#define Sn_IR_PFAIL 0x40
PPP fail bit of Sn_IR.
It is valid only in Sn_MR(P3:P0) = Sn_MR_PPPoE.
Setting for the case that PAP authentication is failed.
Definition at line 1525 of file w5300.h.
Referenced by pppinit_in().
#define Sn_IR_PNEXT 0x20
PPP next phase bit of Sn_IR.
It is valid only in Sn_MR(P3:P0) = Sn_MR_PPPoE.
Setting for the case that the phase is changed during PPPoE connection process.
Definition at line 1533 of file w5300.h.
Referenced by pppinit_in().
#define Sn_IR_PRECV 0x80
PPP receive bit of Sn_IR.
It is valid only in Sn_MR(P3:P0) = Sn_MR_PPPoE.
Setting for the case that option data which is not supported is received.
Definition at line 1517 of file w5300.h.
Referenced by pppinit_in().
#define Sn_IR_RECV 0x04
Receive bit of Sn_IR.
Setting for the case whenever data packet is received from the peer.
Definition at line 1555 of file w5300.h.
#define Sn_IR_SENDOK 0x10
Send OK bit of Sn_IR.
Setting for the case that the Sn_CR_SEND command is completed
Definition at line 1541 of file w5300.h.
Referenced by recv(), send(), and sendto().
#define Sn_IR_TIMEOUT 0x08
Timout bit of Sn_IR.
Setting for the case that ARP timeout or TCP timeout occurs(Sn_IR(Sn_IR_TIMEOUT) = '1')).
Definition at line 1548 of file w5300.h.
Referenced by sendto().
#define Sn_MR_ALIGN (1 << 8)
Alignment bit of Sn_MR.
'0' - No use alignment
'1' - Use alignment
It is only valid on Sn_MR_TCP.
When received data size is of even number and set as '1', data receiving performance can be improved by removing PACKET-INFO(Data Size) that is attached to every receipt data.
Definition at line 1211 of file w5300.h.
Referenced by recv().
#define Sn_MR_CLOSE 0x00
Protocol bits of Sn_MR.
No used.
It configures communication protocol (TCP, UDP, IP RAW, MAC RAW) in each socket
or PPPoE socket to operate with PPPoE server.
Sn_MR_CLOSE : No used
Sn_MR_TCP : TCP
Sn_MR_UDP : UDP
Sn_MR_IPRAW : IP RAW
Sn_MR_MACRAW : MAC RAW
Sn_MR_PPPoE : PPPoE
Definition at line 1273 of file w5300.h.
#define Sn_MR_IGMPv (1 << 5)
IGMP version bit of Sn_MR.
'0' - Using IGMP version 2 (IGMPv2)
'1' - Enable IGMP version 1 (IGMPv1)
It is only valid on Sn_MR_UDP and Sn_MR_MULTI.
It configures IGMP version to send IGMP message such as Join/Leave/Report to multicast-group.
Definition at line 1244 of file w5300.h.
#define Sn_MR_IPRAW 0x03
Protocol bits of Sn_MR.
IP raw.
Refer to Sn_MR_CLOSE.
Definition at line 1294 of file w5300.h.
Referenced by recvfrom().
#define Sn_MR_MACRAW 0x04
Protocol bits of Sn_MR.
MAC raw.
Refer to Sn_MR_CLOSE.
Note:
This mode can be used only in SOCKET0.
Definition at line 1302 of file w5300.h.
Referenced by recvfrom().
#define Sn_MR_MF (1 << 6)
MAC filter bit of Sn_MR.
'0' - Disable MAC filter
'1' - Enable MAC filter
It is only valid on Sn_MR_MACRAW.
When this bit is set as '1', W5300 can receive packet that is belong in itself or broadcasting.
When this bit is set as '0', W5300 can receive all packets on ethernet.
Definition at line 1233 of file w5300.h.
#define Sn_MR_MULTI (1 << 7)
Multicasting bit of Sn_MR.
'0' - Disable multicasting
'1' - Enable multicasting
It is only valid on Sn_MR_UDP.
In order to use multicasting, set its bit, the IP address and port number in Sn_DIPR and Sn_DPORTR respectively before 'Sn_CR = Sn_CR_OPEN'.
Definition at line 1222 of file w5300.h.
#define Sn_MR_ND (1 << 5)
No delayed ack bit of Sn_MR.
'0' - Disable no delayed ack
'1' - Enable no delayed ack
It is only valid on Sn_MR_TCP.
In case that this Bit is set as '1', ACK packet is transmitted right after receiving data packet from the peer.
This Bit is recommended to be set as '1' for TCP performance improvement. In case that this Bit is set as '0', ACK packet is transmitted after the time set in RTR regardless of Data packet receipt.
Definition at line 1258 of file w5300.h.
#define Sn_MR_PPPoE 0x05
Protocol bits of Sn_MR.
PPPoE.
Refer to Sn_MR_CLOSE.
Note:
This mode can be used only in SOCKET0.
S0_MR_PPPoE is temporarily used for PPPoE server connection/termination. After PPPoE session is established, it can be used as another protocol.
Definition at line 1312 of file w5300.h.
Referenced by pppinit(), and pppterm().
#define Sn_MR_TCP 0x01
Protocol bits of Sn_MR.
TCP.
Refer to Sn_MR_CLOSE.
Definition at line 1280 of file w5300.h.
Referenced by close(), loopback_tcpc(), and loopback_tcps().
#define Sn_MR_UDP 0x02
Protocol bits of Sn_MR.
UDP.
Refer to Sn_MR_CLOSE.
Definition at line 1287 of file w5300.h.
Referenced by close(), loopback_udp(), and recvfrom().
#define SOCK_ARP 0x01
It is the status that ARP-request is transmitted in order to acquire destination hardware address.
This status is observed when Sn_CR_SEND is performed at the SOCK_UDP or SOCK_IPRAW, or Sn_CR_CONNECT is performed at the SOCK_INIT.
If hardware address is successfully acquired from destination (when ARP-response is received), it is changed to SOCK_UDP, SOCK_IPRAW or SOCK_SYNSENT.
If it's failed and ARP timeout(Sn_IR(Sn_IR_TIMEOUT)='1') occurs, in case of UDP or IPRAW mode it goes back to the previous status(SOCK_UDP or SOCK_IPRAW), in case of TCP mode it goes to the SOCK_CLOSED.
See also:
Sn_SSR
Note:
ARP-process operates at the SOCK_UDP or SOCK_IPRAW if the current Sn_DIPR is different from the previous Sn_DIPR. If previous and current values of Sn_DIPR are same, ARP-process doesn't operate becase the destination hardware address is already acquired.
Definition at line 1589 of file w5300.h.
#define SOCK_CLOSE_WAIT 0x1C
It is the status that disconnect-request(FIN packet) is received from the peer.
As TCP connection is half-closed, it is possible to transfer data packet. In order to complete the TCP disconnection, Sn_CR_DISCON should be performed.
For SOCKETn close without disconnection-process, Sn_CR_CLOSE can be just performed.
See also:
Sn_SSR
Definition at line 1692 of file w5300.h.
Referenced by loopback_tcpc(), loopback_tcps(), and send().
#define SOCK_CLOSED 0x00
It is the status that resource of SOCKETn is released.
When Sn_CR_DISCON or Sn_CR_CLOSE is performed, or ARP/TCP timout occurs, it is changed to SOCK_CLOSED regardless of the previous Sn_SSR value.
See also:
Sn_SSR
Definition at line 1579 of file w5300.h.
Referenced by loopback_tcpc(), loopback_tcps(), loopback_udp(), send(), and sendto().
#define SOCK_CLOSING 0x1A
It is the status that SOCKETn is closed.
Refer to SOCK_FIN_WAIT.
Definition at line 1678 of file w5300.h.
#define SOCK_ESTABLISHED 0x17
It is the status that TCP connection is established.
It is changed to SOCK_ESTABLISHED when SYN packet from "TCP CLIENT" is successfully processed at the SOCK_LISTEN, or Sn_CR_CONNECT is successfully performed. At this status, DATA packet can be transferred, that is, Sn_CR_SEND or Sn_CR_RECV command can be performed.
See also:
Sn_SSR
Definition at line 1655 of file w5300.h.
Referenced by loopback_tcpc(), loopback_tcps(), and send().
#define SOCK_FIN_WAIT 0x18
It is the status that SOCKETn is closed.
It is observed in the disconnect-process of active close or passive close.
It is changed to SOCK_CLOSED when disconnect-process is successfully finished or TCP timeout occurs(Sn_IR(Sn_IR_TIMEOUT)='1').
See also:
Sn_SSR
Definition at line 1666 of file w5300.h.
#define SOCK_INIT 0x13
It is the status that SOCKETn is open as TCP mode.
It is changed to SOCK_INIT when Sn_MR(P3:P0) is Sn_MR_TCP and Sn_CR_OPEN is performed. It is the initial step of TCP connection establishment.
It is possible to perform Sn_CR_LISTEN at the "TCP SERVER" mode and Sn_CR_CONNECT command at the "TCP CLIENT".
See also:
Sn_SSR
Definition at line 1607 of file w5300.h.
Referenced by listen(), loopback_tcpc(), and loopback_tcps().
#define SOCK_IPRAW 0x32
It is the status that SOCKETn is open as IPRAW mode.
It is changed to SOCK_IPRAW when Sn_MR(P3:P0) is Sn_MR_IPRAW and Sn_CR_OPEN is performed.IP packet can be transferred without connection such like SOCK_UDP.
See also:
Sn_SSR
Definition at line 1720 of file w5300.h.
#define SOCK_LAST_ACK 0x1D
It is the status that SOCKETn is closed.
Refer to SOCK_FIN_WAIT.
Definition at line 1703 of file w5300.h.
#define SOCK_LISTEN 0x14
It is the status that SOCKETn operates as "TCP SERVER" and waits for connection-request (SYN packet) from "TCP CLIENT".
When Sn_CR_LISTEN is performed, it is changed to SOCK_LISTEN. When connect-request(SYN packet) from "TCP CLIENT" is successfully processed, SOCK_LISTEN is changed to SOCK_ESTABLISHED.
If it is failed, TCP timout occurs(Sn_IR(Sn_IR_TIMEOUT)='1') and changed to SOCK_CLOSED.
See also:
Sn_SSR
Definition at line 1618 of file w5300.h.
#define SOCK_MACRAW 0x42
It is the status that SOCKET0 is open as MACRAW mode.
It is changed to SOCK_MACRAW in case of S0_MR(P3:P0) = S0_MR_MACRAW and Sn_CR_OPEN is performed.
MAC packet(Ethernet frame) can be transferred such like SOCK_UDP.
See also:
Sn_SSR
Definition at line 1730 of file w5300.h.
#define SOCK_PPPoE 0x5F
It is the status that SOCKET0 is open as PPPoE mode.
It is changed to SOCK_PPPoE in case of S0_MR(P3:P0) = S0_MR_PPPoE and Sn_CR_OPEN is performed.
It is temporarily used at the PPPoE connection. For the detail, refer to "How to use PPPoE in W5300".
See also:
Sn_SSR
Definition at line 1740 of file w5300.h.
Referenced by pppterm().
#define SOCK_SYNRECV 0x16
It is the status that connect-request(SYN packet) is received from "TCP CLIENT".
It is automatically changed to SOCK_ESTABLISHED when W5300 successfully transmits connect-accept(SYN/ACK packet) to the "TCP CLIENT".
If it is failed, TCP timeout occurs(Sn_IR(Sn_IR_TIMEOUT)='1'), and it is changed to SOCK_CLOSED.
See also:
Sn_SSR
Definition at line 1644 of file w5300.h.
#define SOCK_SYNSENT 0x15
It is the status that connect-request(SYN packet) is transmitted to "TCP SERVER".
This status shows changing process from SOCK_INIT to SOCK_ESTABLISHED by Sn_CR_CONNECT.
At this status, if connect-accept(SYN/ACK packet) is received from "TCP SERVER", it is automatically changed to SOCK_ESTABLISHED. If SYN/ACK packet is not received from the "TCP SERVER" before TCP Timeout occurs (Sn_IR(Sn_IR_TIMEOUT)='1'), it is changed to SOCK_CLOSED.
See also:
Sn_SSR
Definition at line 1631 of file w5300.h.
#define SOCK_TIME_WAIT 0x1B
It is the status that SOCKETn is closed.
Refer to SOCK_FIN_WAIT.
Definition at line 1685 of file w5300.h.
#define SOCK_UDP 0x22
It is the status that SOCKETn is open as UDP mode.
It is changed to SOCK_UDP when Sn_MR(P3:P0) is Sn_MR_UDP and Sn_CR_OPEN is performed. DATA packet can be transferred without connection that is necessary to TCP mode SOCKET.
See also:
Sn_SSR
Definition at line 1710 of file w5300.h.
Referenced by loopback_udp().
#define TMS23R (TMS01R + 2)
Refer to TMS01R.
Definition at line 296 of file w5300.h.
Referenced by sysinit().
#define TMS45R (TMS01R + 4)
Refer to TMS01R.
Definition at line 297 of file w5300.h.
Referenced by sysinit().
#define TMS67R (TMS01R + 6)
Refer to TMS01R.
Definition at line 298 of file w5300.h.
Referenced by sysinit().
Function Documentation
uint16 getFMTUR (void)
It gets the fragmented MTU value of ICMP message.
Returns:
The fragmented MTU value
See also:
IR_FMTU, Sn_MSSR, setSn_MSSR()
Definition at line 245 of file w5300.c.
References FMTUR, and IINCHIP_READ().
void getGAR (uint8 * addr)
It gets the gateway IP address.
Parameters:
[out] addr Storage location for input the gateway IP address. It should be allocated 4bytes size.
See also:
setGAR()
Definition at line 130 of file w5300.c.
References GAR, and IINCHIP_READ().
Referenced by Main().
void uint16 getIDR (void)
It gets the ID of W5300.
Returns:
0x5300
Definition at line 274 of file w5300.c.
References IDR, and IINCHIP_READ().
uint32 getIINCHIP_RxMAX (SOCKET s)
It gets the max size of internal RX memory of each SOCKET.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
It returns RXMEM_SIZE value of s-th SOCKET
Definition at line 788 of file w5300.c.
References RXMEM_SIZE.
uint32 getIINCHIP_TxMAX (SOCKET s)
It gets the max size of internal TX memory of each SOCKET.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
It returns TXMEM_SIZE value of s-th SOCKET
Definition at line 783 of file w5300.c.
References TXMEM_SIZE.
Referenced by close(), send(), and sendto().
uint16 getIMR (void)
It gets IMR value.
Returns:
The IMR value
See also:
setIMR()
Definition at line 102 of file w5300.c.
References IINCHIP_READ(), and IMR.
uint16 getIR (void)
It gets IR value.
Returns:
The IR value
See also:
setIR()
Definition at line 93 of file w5300.c.
References IINCHIP_READ(), and IR.
uint16 getMR (void)
It gets MR value.
Returns:
The value of MR
See also:
setMR()
Definition at line 77 of file w5300.c.
References MR.
Referenced by pppinit(), and pppterm().
uint16 getPATR (void)
It gets PATR value.
Returns:
The value of PATR.
If PAP it returns 0xC023.
If CHAP it returns 0xC223.
Definition at line 191 of file w5300.c.
References IINCHIP_READ(), and PATR.
Referenced by pppinit_in().
void getPDHAR (uint8 * addr)
It gets the PPPoE server hardware address.
Parameters:
[out] addr Storage location for input the source IP address. It should be allocated 6bytes size.
Definition at line 219 of file w5300.c.
References IINCHIP_READ(), and PDHAR.
Referenced by Main().
uint8 getPMAGICR (void)
It gets PMAGICR value.
Returns:
The value of PMAGICR.
See also:
setPMAGICR()
Definition at line 205 of file w5300.c.
References IINCHIP_READ(), and PMAGICR.
uint16 getPn_BDPTHR (uint8 p)
It gets the buffer depth of PIN "BRDYn".
Parameters:
[in] p The number of PIN "BRDYn". It is valid when 0 <= p <= 3.
Returns:
The buffer depth of PIN "BRDYn".
See also:
setPn_BDPTHR(), Pn_BRDYR
Definition at line 263 of file w5300.c.
References IINCHIP_READ(), and Pn_BDPTHR.
uint8 getPn_BRDYR (uint8 p)
It gets Pn_BRDYR value.
Parameters:
[in] p The number of PIN "BRDYn". It is valid when 0 <= p <= 3.
Returns:
The configuration value of Pn_BRDYR.
See also:
setPn_BRDYR(), Pn_BDPTHR
Definition at line 253 of file w5300.c.
References IINCHIP_READ(), and Pn_BRDYR.
uint16 getPSIDR (void)
It gets PSIDR value.
Returns:
The value of PSIDR.
Note:
PSIDR is read-only register.
However, in order to set PPP session ID(PSIDR), You can do it by writing S0_DPORTR to PPP session ID.
Definition at line 214 of file w5300.c.
References IINCHIP_READ(), and PSIDR.
Referenced by Main().
uint8 getPTIMER (void)
It gets PTIMER value.
Returns:
The value of PTIMER. The unit is 25ms.
See also:
setPTIMER()
Definition at line 196 of file w5300.c.
References IINCHIP_READ(), and PTIMER.
uint8 getRCR (void)
It gets RCR value.
Returns:
The value of RCR
See also:
setRCR()
Definition at line 181 of file w5300.c.
References IINCHIP_READ(), and RCR.
uint16 getRTR (void)
It gets RTR value.
Returns:
The value of RTR. The unit is 100us.
See also:
setRTR()
Definition at line 172 of file w5300.c.
References IINCHIP_READ(), and RTR.
void getSHAR (uint8 * addr)
It gets the source hardware address.
Parameters:
[out] addr Storage location for input the source hardware address. It should be allocated 6bytes size.
See also:
setSHAR()
Definition at line 114 of file w5300.c.
References IINCHIP_READ(), and SHAR.
Referenced by Main().
void getSIPR (uint8 * addr)
It gets the source IP address.
Parameters:
[out] addr Storage location for input the source IP address. It should be allocated 4bytes size.
See also:
setSIPR()
Definition at line 156 of file w5300.c.
References IINCHIP_READ(), and SIPR.
Referenced by Main().
uint8 getSn_CR (SOCKET s)
It gets Sn_CR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The command value of s-th SOCKET.
See also:
setSn_CR()
Definition at line 295 of file w5300.c.
References IINCHIP_READ(), and Sn_CR.
void getSn_DHAR (SOCKET s, uint8 * addr)
It gets Sn_DHAR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[out] addr Storage location for input the destination hardware address of s-th SOCKET. It should be allocated 6bytes size.
Note:
It is also used when you get the PPPoE server hardware address.
Refer to getPDHAR(), PDHAR
See also:
setSn_DHAR()
Definition at line 348 of file w5300.c.
References IINCHIP_READ(), and Sn_DHAR.
void getSn_DIPR (SOCKET s, uint8 * addr)
It gets Sn_DIPR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[out] addr Storage location for input the destination IP address of s-th SOCKET. It should be allocated 4bytes size.
See also:
setSn_DIPR()
Definition at line 377 of file w5300.c.
References IINCHIP_READ(), and Sn_DIPR.
uint8 getSn_FRAGR (SOCKET s)
It gets Sn_FRAGR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The Sn_FRAGR value of s-th SOCKET.
See also:
setSn_FRAGR()
Definition at line 501 of file w5300.c.
References IINCHIP_READ(), and Sn_FRAGR.
uint8 getSn_IMR (SOCKET s)
It gets Sn_IMR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The interrupt mask value of s-th SOCKET.
See also:
setSn_IMR(), Sn_IR, IR_SnINT
Definition at line 305 of file w5300.c.
References IINCHIP_READ(), and Sn_IMR.
uint8 getSn_IR (SOCKET s)
It gets Sn_IR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The interrupt status of s-th SOCKET.
See also:
setSn_IR(), Sn_IMR, IR_SnINT
Definition at line 314 of file w5300.c.
References IINCHIP_READ(), Sn_IR, and SOCK_INT.
Referenced by loopback_tcpc(), loopback_tcps(), pppinit(), pppinit_in(), pppterm(), recv(), send(), and sendto().
uint8 getSn_KPALVTR (SOCKET s)
It gets Sn_KPALVTR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The Sn_KPALVTR value of s-th SOCKET to be set.
See also:
setSn_KPALVTR()
Definition at line 405 of file w5300.c.
References IINCHIP_READ(), and Sn_KPALVTR.
uint16 getSn_MR (SOCKET s)
It gets Sn_MR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The mode value of s-th SOCKET.
See also:
setSn_MR()
Definition at line 286 of file w5300.c.
References IINCHIP_READ(), and Sn_MR.
Referenced by close().
uint16 getSn_MSSR (SOCKET s)
It gets Sn_MSSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The value of Sn_MSSR
See also:
setSn_MSSR()
Definition at line 392 of file w5300.c.
References IINCHIP_READ(), and Sn_MSSR.
uint8 getSn_PROTOR (SOCKET s)
It gets Sn_PROTOR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The protocol number of s-th SOCKET.
See also:
setSn_PROTOR()
Definition at line 472 of file w5300.c.
References IINCHIP_READ(), and Sn_PROTOR.
uint16 getSn_RX_FIFOR (SOCKET s)
It gets Sn_RX_FIFOR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The data value to be read from internal RX memory of of s-th SOCKET, through Sn_RX_FIFOR.
Definition at line 464 of file w5300.c.
References IINCHIP_READ(), and Sn_RX_FIFOR.
uint32 getSn_RX_RSR (SOCKET s)
It gets Sn_RX_RSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
It returns the byte size of received data in internal RX memory of s-th SOCKET.
Warning:
Warning:
The host can read the wrong value of Sn_RX_RSR.
Because Sn_TX_RSR is not changed by 'system bus signal' but changed by synchronous 'NIC_CLK' clock.
To prevented this problem, the host should read it until the previous value is equal to the curruent.
Definition at line 444 of file w5300.c.
References IINCHIP_READ(), and Sn_RX_RSR.
Referenced by loopback_tcpc(), loopback_tcps(), loopback_udp(), pppinit_in(), and recv().
uint8 getSn_SSR (SOCKET s)
It gets Sn_SSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The status value of s-th SOCKET.
Warning:
Warning:
The host can read the wrong value of Sn_SSR.
Because Sn_SSR is not changed by 'system bus signal' but changed by synchronous 'NIC_CLK' clock.
To prevented this problem, the host should read it until the previous value is equal to the curruent.
Definition at line 334 of file w5300.c.
References IINCHIP_READ(), and Sn_SSR.
Referenced by listen(), loopback_tcpc(), loopback_tcps(), loopback_udp(), pppterm(), send(), sendto(), and socket().
uint8 getSn_TOSR (SOCKET s)
It gets Sn_TOSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The TOS value of s-th SOCKET.
See also:
setSn_TOSR()
Definition at line 483 of file w5300.c.
References IINCHIP_READ(), and Sn_TOSR.
uint8 getSn_TTLR (SOCKET s)
It gets Sn_TTLR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The TTL value of s-th SOCKET.
See also:
setSn_TTLR()
Definition at line 492 of file w5300.c.
References IINCHIP_READ(), and Sn_TTLR.
uint32 getSn_TX_FSR (SOCKET s)
It gets Sn_TX_FSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
It returns the free size of internal TX memory(the byte size of transmittable data) of s-th SOCKET.
Warning:
Warning:
The host can read the wrong value of Sn_TX_FSR.
Because Sn_TX_FSR is not changed by 'system bus signal' but changed by synchronous 'NIC_CLK' clock.
To prevented this problem, the host should read it until the previous value is equal to the curruent.
Definition at line 430 of file w5300.c.
References IINCHIP_READ(), and Sn_TX_FSR.
Referenced by close(), and send().
uint32 getSn_TX_WRSR (SOCKET s)
It gets Sn_TX_WRSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The byte size of data written in internal TX memory of s-th SOCKET.
See also:
setSn_TX_WRSR()
Definition at line 417 of file w5300.c.
References IINCHIP_READ(), and Sn_TX_WRSR.
void getSUBR (uint8 * addr)
It gets the subnet mask address.
Parameters:
[out] addr Storage location for input the subnet mask address. It should be allocated 4bytes size.
See also:
getSUBR()
Definition at line 143 of file w5300.c.
References IINCHIP_READ(), and SUBR.
Referenced by Main().
void getUIPR (uint8 * addr)
It gets the unreachable destination IP address of ICMP message.
Parameters:
[out] addr Storage location for input the unreachable destination IP address. It should be allocated 4bytes size.
Note:
PDHAR is read-only register.
However, in order to set PPPoE server hardware address(PDHAR), You can do it by writing S0_DHAR to PPPoe server hardware address.
See also:
getUPORTR(), IR_DPUR
Definition at line 232 of file w5300.c.
References IINCHIP_READ(), and UIPR.
uint16 getUPORTR (void)
It gets the unreachable destination port number of ICMP message.
Returns:
The unreachable destination port number
See also:
getUIPR(), IR_DPUR
Definition at line 240 of file w5300.c.
References IINCHIP_READ(), and UPORTR.
void iinchip_init (void)
It initializes W5300.
It initializes W5300 by soft reset and decides the host interface mode by configuration MR.
Note:
You can modify this function to configure MR_WDF, MR_RDH, MR_FS, MR_DBS, MR_PB, MR_PPPoE.
Definition at line 518 of file w5300.c.
References MR, MR_IND, MR_RST, and wait_10ms().
Referenced by Main().
void iinchip_irq (void)
It handles the interrupt of W5300.
Todo:
You should do implement your interrupt request routine instead of this function. If you want to use ISR, this function should be mapped in your ISR handler.
Definition at line 536 of file w5300.c.
References IINCHIP_CRITICAL_SECTION_ENTER, IINCHIP_CRITICAL_SECTION_EXIT, IINCHIP_READ(), IINCHIP_WRITE(), IR, IR_DPUR, IR_IPCF, IR_SnINT, MAX_SOCK_NUM, Sn_IR, SOCK_INT, UIPR, and UPORTR.
uint16 IINCHIP_READ (uint32 addr)
Basic I/O function.
It reads a value from a register
Parameters:
[in] addr register address
Returns:
the value of register
Note:
If you define __DEF_IINCHIP_DIRECT_MODE__, you can use the below code instead of this function for the better performance.
 #define IINCHIP_READ(uint32 addr) (*(vint16*)addr)
Definition at line 52 of file w5300.c.
References IDM_AR, IDM_DR, IINCHIP_CRITICAL_SECTION_ENTER, and IINCHIP_CRITICAL_SECTION_EXIT.
Referenced by getFMTUR(), getGAR(), getIDR(), getIMR(), getIR(), getPATR(), getPDHAR(), getPMAGICR(), getPn_BDPTHR(), getPn_BRDYR(), getPSIDR(), getPTIMER(), getRCR(), getRTR(), getSHAR(), getSIPR(), getSn_CR(), getSn_DHAR(), getSn_DIPR(), getSn_FRAGR(), getSn_IMR(), getSn_IR(), getSn_KPALVTR(), getSn_MR(), getSn_MSSR(), getSn_PROTOR(), getSn_RX_FIFOR(), getSn_RX_RSR(), getSn_SSR(), getSn_TOSR(), getSn_TTLR(), getSn_TX_FSR(), getSn_TX_WRSR(), getSUBR(), getUIPR(), getUPORTR(), iinchip_irq(), recv(), recvfrom(), setSn_CR(), setSn_KPALVTR(), setSn_PROTOR(), socket(), sysinit(), and wiz_read_buf().
void IINCHIP_WRITE (uint32 addr, uint16 data)
Basic I/O function.
It writes a value to a register
Parameters:
[in] addr register address
[in] data write data
Returns:
void
Note:
If you define __DEF_IINCHIP_DIRECT_MODE__, you can use the below code instead of this function for the better performance.
 #define IINCHIP_WRITE(uint32 addr,uint16 data)  ((*(vint16*)addr) = data)
Definition at line 65 of file w5300.c.
References IDM_AR, IDM_DR, IINCHIP_CRITICAL_SECTION_ENTER, and IINCHIP_CRITICAL_SECTION_EXIT.
Referenced by connect(), iinchip_irq(), recv(), sendto(), setGAR(), setIMR(), setIR(), setPMAGICR(), setPn_BDPTHR(), setPn_BRDYR(), setPTIMER(), setRCR(), setRTR(), setSHAR(), setSIPR(), setSn_CR(), setSn_DHAR(), setSn_DIPR(), setSn_DPORTR(), setSn_FRAGR(), setSn_IMR(), setSn_IR(), setSn_KPALVTR(), setSn_MR(), setSn_MSSR(), setSn_PROTOR(), setSn_TOSR(), setSn_TTLR(), setSn_TX_FIFOR(), setSn_TX_WRSR(), setSUBR(), socket(), sysinit(), and wiz_write_buf().
uint8 pppinit (uint8 * id, uint8 idlen, uint8 * passwd, uint8 passwdlen)
It initializes to PPPoE of W5300.
It initiazes W5300 for PPPoE and calls pppinit_in() for PPPoE processing phase.
For the detail, refer to "How to use PPPoE in W5300".
Parameters:
[in] id User ID for connecting to a PPPoE server
[in] idlen Length of id
[in] passwd User password for connecting to a PPPoE server
[in] passwdlen Length of passwd
Returns:
It returns the result of pppinit_in()
Definition at line 1116 of file w5300.c.
References getMR(), getSn_IR(), MR_FS, MR_PPPoE, pppinit_in(), setMR(), setPMAGICR(), setPTIMER(), setSn_CR(), setSn_IR(), setSn_MR(), Sn_CR_CLOSE, Sn_CR_OPEN, and Sn_MR_PPPoE.
Referenced by Main().
void pppterm (uint8 * mac, uint16 sessionid)
It terminates PPPoE connection.
For the detail, refer to "How to use PPPoE in W5300".
Parameters:
[in] mac PPPoE server hardware address occupied by pppinit() or your PPPoE-process code.
[in] sessionid session ID occupied by pppinit() or your PPPoE-process code.
Definition at line 1143 of file w5300.c.
References getMR(), getSn_IR(), getSn_SSR(), MR_PPPoE, setMR(), setSn_CR(), setSn_DHAR(), setSn_DPORTR(), setSn_IR(), setSn_MR(), Sn_CR_CLOSE, Sn_CR_OPEN, Sn_CR_PDISCON, Sn_MR_PPPoE, SOCK_PPPoE, and wait_10ms().
Referenced by Main().
void setGAR (uint8 * addr)
It sets the gateway IP address.
Parameters:
[in] addr Pointer to the gateway IP address to be set
See also:
getGAR()
Definition at line 137 of file w5300.c.
References GAR, and IINCHIP_WRITE().
Referenced by Main().
void setIMR (uint16 mask)
It sets IMR value.
Parameters:
[in] mask The mask value to be set
See also:
getIMR()
Definition at line 106 of file w5300.c.
References IINCHIP_WRITE(), and IMR.
void setIR (uint16 val)
It sets IR value.
Parameters:
[in] val The value to be set
See also:
getIR()
Definition at line 97 of file w5300.c.
References IINCHIP_WRITE(), and IR.
void setMR (uint16 val)
It sets MR value.
Parameters:
[in] val The value to be set
See also:
getMR()
Definition at line 81 of file w5300.c.
References MR.
Referenced by pppinit(), and pppterm().
void setPMAGICR (uint8 magic)
It sets PTIMER value.
Parameters:
[in] magic The byte of 4byts MAGIC number for PPPoE
See also:
getPMAGICR()
Definition at line 209 of file w5300.c.
References IINCHIP_WRITE(), and PMAGICR.
Referenced by pppinit().
void setPn_BDPTHR (uint8 p, uint16 depth)
It sets the buffer depth of PIN "BRDYn".
Parameters:
[in] p The number of PIN "BRDYn". It is valid when 0 <= p <= 3.
[in] depth The buffer depth of PIN "BRDYn" to be set.
See also:
getPn_BDPTHR(), Pn_BRDYR
Definition at line 267 of file w5300.c.
References IINCHIP_WRITE(), and Pn_BDPTHR.
setPn_BRDYR (uint8 p, uint8 cfg)
It sets Pn_BRDYR value.
Parameters:
[in] p The number of PIN "BRDYn". It is valid when 0 <= p <= 3.
[in] cfg The configuration values of Pn_BRDYR to be set.
See also:
getPn_BRDYR(), Pn_BDPTHR
Definition at line 257 of file w5300.c.
References IINCHIP_WRITE(), and Pn_BRDYR.
void setPTIMER (uint8 time)
It sets PTIMER value.
Parameters:
[in] time LCP echo-request transmittion timer value to be set. The unit is 25ms.
See also:
getPTIMER()
Definition at line 200 of file w5300.c.
References IINCHIP_WRITE(), and PTIMER.
Referenced by pppinit().
void setRCR (uint8 retry)
It sets RCR value.
Parameters:
[in] retry The retry count of retransmittion to be set.
See also:
getRCR()
Definition at line 185 of file w5300.c.
References IINCHIP_WRITE(), and RCR.
void setRTR (uint16 timeout)
It sets RTR value.
Parameters:
[in] timeout The timeout value to be set. The unit is 100us.
See also:
getRTR()
Definition at line 176 of file w5300.c.
References IINCHIP_WRITE(), and RTR.
void setSHAR (uint8 * addr)
It sets the source hardware address.
Parameters:
[in] addr Pointer to the source hardware address to be set.
See also:
getSHAR()
Definition at line 123 of file w5300.c.
References IINCHIP_WRITE(), and SHAR.
Referenced by Main().
void setSIPR (uint8 * addr)
It sets the source IP address.
Parameters:
[in] addr Pointer to the source IP address to be set
See also:
getSIR()
Definition at line 163 of file w5300.c.
References IINCHIP_WRITE(), and SIPR.
Referenced by Main().
void setSn_CR (SOCKET s, uint16 com)
It sets Sn_CR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] com The command value of s-th SOCKET.
Note:
It is blocked until Sn_CR is cleared.
See also:
getSn_CR()
Definition at line 299 of file w5300.c.
References IINCHIP_READ(), IINCHIP_WRITE(), and Sn_CR.
Referenced by close(), connect(), disconnect(), listen(), pppinit(), pppinit_in(), pppterm(), recv(), recvfrom(), send(), sendto(), and socket().
void setSn_DHAR (SOCKET s, uint8 * addr)
It sets Sn_DHAR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] addr Pointer to the destination hardware address of s-th SOCKET to be set.
Note:
It is also used when you set PPPoE server hardware address.
Refer to PDHAR
See also:
getSn_DHAR()
Definition at line 358 of file w5300.c.
References IINCHIP_WRITE(), and Sn_DHAR.
Referenced by pppterm().
void setSn_DIPR (SOCKET s, uint8 * addr)
It sets Sn_DIPR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] addr Pointer to the destination IP address of s-th SOCKET to be set.
See also:
getSn_DIPR()
Definition at line 386 of file w5300.c.
References IINCHIP_WRITE(), and Sn_DIPR.
void setSn_DPORTR (SOCKET s, uint16 port)
It sets Sn_DPORTR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] port The desintinaton port number of s-th SOCKET
Note:
It is also used when you set the PPP session ID.
Refer to PSIDR
Definition at line 372 of file w5300.c.
References IINCHIP_WRITE(), and Sn_DPORTR.
Referenced by pppterm().
void setSn_FRAGR (SOCKET s, uint8 frag)
It sets Sn_FRAGR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] frag The Sn_FRAGR value of s-th SOCKET to be set.
Note:
W5300 doesn't support the packet fragment at the IP layer.
Even though Sn_FRAGR is configured, IP data is not fragmented.
See also:
getSn_FRAGR()
Definition at line 506 of file w5300.c.
References IINCHIP_WRITE(), and Sn_FRAGR.
void setSn_IMR (SOCKET s, uint8 mask)
It sets Sn_IMR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] mask The interrupt mask value of s-th SOCKET.
See also:
getSn_IMR(), Sn_IR, IR_SnINT
Definition at line 309 of file w5300.c.
References IINCHIP_WRITE(), and Sn_IMR.
void setSn_IR (SOCKET s, uint8 ir)
It sets Sn_IR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] ir The interrupt status of s-th SOCKET to be cleared.
See also:
getSn_IR(), Sn_IMR, IR_SnINT
Definition at line 322 of file w5300.c.
References IINCHIP_WRITE(), Sn_IR, and SOCK_INT.
Referenced by close(), loopback_tcpc(), loopback_tcps(), pppinit(), pppinit_in(), pppterm(), recv(), send(), and sendto().
void setSn_KPALVTR (SOCKET s, uint8 time)
It sets Sn_KPALVTR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] time The keep alive timer value of s-th SOCKET to be set. The unit is 5 seconds.
Note:
When Sn_KPALVTR > 0, KEEP ALIVE(KA) packet is automatically transmitted and Sn_CR_SEND_KEEP is ignored.
When Sn_KPALVTR = 0, KA packet is manually transmitted by Sn_CR_SEND_KEEP.
See also:
getSn_KPALVTR()
Definition at line 410 of file w5300.c.
References IINCHIP_READ(), IINCHIP_WRITE(), and Sn_KPALVTR.
void setSn_MR (SOCKET s, uint16 mode)
It sets Sn_MR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] mode The mode value of s-th SOCKETn.
See also:
getSn_MR()
Definition at line 290 of file w5300.c.
References IINCHIP_WRITE(), and Sn_MR.
Referenced by pppinit(), and pppterm().
void setSn_MSSR (SOCKET s, uint16 mss)
It sets Sn_MSSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] mss The MSS value of s-th SOCKET to be set.
Note:
When receiving the fragment MTU of ICMP message at UDP mode, You should be set Sn_MSSR to FMTUR by using this function.
Refer to FMTUR, IR_FMTU.
See also:
getSn_MSSR()
Definition at line 397 of file w5300.c.
References IINCHIP_WRITE(), and Sn_MSSR.
void setSn_PROTOR (SOCKET s, uint8 pronum)
It sets Sn_PROTOR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] pronum The protocol number of s-th SOCKET to be set. pronum does't support both 0x06(TCP) and 0x11(UDP) number.
See also:
getSn_PROTOR()
Definition at line 476 of file w5300.c.
References IINCHIP_READ(), IINCHIP_WRITE(), and Sn_PROTOR.
void setSn_TOSR (SOCKET s, uint8 tos)
It sets Sn_TOSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] tos The TOS value of s-th SOCKET to be set.
See also:
getSn_TOSR()
Definition at line 487 of file w5300.c.
References IINCHIP_WRITE(), and Sn_TOSR.
void setSn_TTLR (SOCKET s, uint8 ttl)
It sets Sn_TTLR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] ttl The TTL value of s-th SOCKET to be set.
See also:
getSn_TTLR()
Definition at line 496 of file w5300.c.
References IINCHIP_WRITE(), and Sn_TTLR.
void setSn_TX_FIFOR (SOCKET s, uint16 data)
It sets Sn_TX_FIFOR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
data The data value to be written into internal TX memory of of s-th SOCKET, through Sn_TX_FIFOR.
Definition at line 459 of file w5300.c.
References IINCHIP_WRITE(), and Sn_TX_FIFOR.
void setSn_TX_WRSR (SOCKET s, uint32 size)
It gets Sn_KPALVTR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] size The byte size of data written in interanl TX memory of s-th SOCKET.
See also:
getSn_TX_WRSR()
Definition at line 424 of file w5300.c.
References IINCHIP_WRITE(), and Sn_TX_WRSR.
Referenced by pppinit_in(), recv(), send(), and sendto().
void setSUBR (uint8 * addr)
It sets the subnet mask address.
Parameters:
[in] addr Pointer to the subnet mask address to be set
See also:
setSUBR()
Definition at line 150 of file w5300.c.
References IINCHIP_WRITE(), and SUBR.
Referenced by Main().
uint8 sysinit (uint8 * tx_size, uint8 * rx_size)
It allocate internal TX/RX memory of each SOCKET.
Parameters:
[in] tx_size The pointer to allocate tx_size[n] to the internal TX memory of each SOCKET.
(0 <= n <= MAX_SOCK_NUM-1).
TX memory size of each SOCKET is configurable in the range of 0~64Kbytes. Total memory size of each SOCKET's TX memory should be the multiple of 8.
[in] rx_size The pointer to allocate rx_size[n] to the internal RX memory of each SOCKET.
(0 <= n <= MAX_SOCK_NUM-1).
RX memory size of each SOCKET is configurable in the range of 0~64Kbytes. Total memory size of each SOCKET's TX memory and RX memory should be 128Kbytes.
Returns:
If success, it returns 1. Otherwize 0.
Definition at line 577 of file w5300.c.
References IINCHIP_READ(), IINCHIP_WRITE(), MAX_SOCK_NUM, MTYPER, RMS01R, RMS23R, RMS45R, RMS67R, RXMEM_SIZE, TMS01R, TMS23R, TMS45R, TMS67R, and TXMEM_SIZE.
Referenced by Main().
void wait_10ms (uint32 ms)
Delay function.
Parameters:
[in] ms - wait time It waits for the ms time.
Todo:
These delay functions depend on the MCU. Therefore, These function should be replaced with yours.
Definition at line 1200 of file w5300.c.
References wait_1ms().
Referenced by close(), iinchip_init(), pppinit_in(), and pppterm().
uint32 wiz_read_buf (SOCKET s, uint8 * buf, uint32 len)
It copies data to your buffer from internal RX memory.
It copies the len bytes of internal RX memory of s-th SOCKET to buf through Sn_RX_FIFOR.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[out] buf Destination buffer to copy
The length of buf should be equal or greater than len + 1, in order to prevent the memory violation.
[in] len bytes of internal RX memory of s-th SOCKET to copy.
Returns:
The copied byte number
Note:
In case using interrupt or multi-task, it is protected with IINCHIP_CRITICAL_SECTION_ENTER() & IINCHIP_CRITICAL_SECTION_EXIT() while Sn_RX_FIFOR read.
If no use, it can be occured some problem such as invalid PACKET_INFO or DATA.
Definition at line 714 of file w5300.c.
References IDM_AR, IDM_DR, IINCHIP_CRITICAL_SECTION_ENTER, IINCHIP_CRITICAL_SECTION_EXIT, IINCHIP_READ(), and Sn_RX_FIFOR.
Referenced by pppinit_in(), recv(), and recvfrom().
uint32 wiz_write_buf (SOCKET s, uint8 * buf, uint32 len)
It copies data to interna1 TX memory.
It copies the len bytes of buf to internal TX memory of s-th SOCKET through Sn_TX_FIFOR.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] buf Source buffer to copy from
[in] len bytes of data to copy.
Returns:
The copied byte number
Note:
In case using interrupt or multi-task, it is protected with IINCHIP_CRITICAL_SECTION_ENTER() & IINCHIP_CRITICAL_SECTION_EXIT() while Sn_TX_FIFOR write.
If no use, it can be occured some problem such that invalid DATA are transmitted.
Definition at line 648 of file w5300.c.
References IDM_AR, IDM_DR, IINCHIP_CRITICAL_SECTION_ENTER, IINCHIP_CRITICAL_SECTION_EXIT, IINCHIP_WRITE(), and Sn_TX_FIFOR.
Referenced by pppinit_in(), send(), and sendto().