W5300 - SOCKET APIs: w5300.c File Reference
w5300.c File Reference
Detailed Description
Implementation of W5300 I/O fucntions
This file implements the basic I/O fucntions that access a register of W5300(IINCHIP_REG).
Revision History :
Date Version Author Description
24/03/2008 1.0.0 MidnightCow Release with W5300 launching
01/05/2008 1.0.1 MidnightCow Refer to M_01052008.
Modify a logical error in iinchip_irq().
15/05/2008 1.1.0 MidnightCow Refer to M_15052008.
Delete getSn_DPORTR() because Sn_DPORTR is write-only.
Replace 'Sn_DHAR2' with 'Sn_DIPR2' in getSn_DIPR().
08/08/2008 1.2.0 MidnightCow & Gorulko Dmitry Refer to M_08082008.
Add IINCHIP_CRITICAL_SECTION_ENTER() & IINCHIP_CRITICAL_SECTION_EXIT() to wiz_read_buf() and wiz_write_buf().
Definition in file w5300.c.
#include "w5300.h"
#include "lstring.h"
#include "md5.h"
Defines
#define PPP_OPTION_BUF_LEN 64
Functions
uint16 IINCHIP_READ (uint32 addr)
Basic I/O function.
void IINCHIP_WRITE (uint32 addr, uint16 data)
Basic I/O function.
uint16 getMR (void)
It gets MR value.
void setMR (uint16 val)
It sets MR value.
uint16 getIR (void)
It gets IR value.
void setIR (uint16 val)
It sets IR value.
uint16 getIMR (void)
It gets IMR value.
void setIMR (uint16 mask)
It sets IMR value.
void getSHAR (uint8 *addr)
It gets the source hardware address.
void setSHAR (uint8 *addr)
It sets the source hardware address.
void getGAR (uint8 *addr)
It gets the gateway IP address.
void setGAR (uint8 *addr)
It sets the gateway IP address.
void getSUBR (uint8 *addr)
It gets the subnet mask address.
void setSUBR (uint8 *addr)
It sets the subnet mask address.
void getSIPR (uint8 *addr)
It gets the source IP address.
void setSIPR (uint8 *addr)
It sets the source IP address.
uint16 getRTR (void)
It gets RTR value.
void setRTR (uint16 timeout)
It sets RTR value.
uint8 getRCR (void)
It gets RCR value.
void setRCR (uint8 retry)
It sets RCR value.
uint16 getPATR (void)
It gets PATR value.
uint8 getPTIMER (void)
It gets PTIMER value.
void setPTIMER (uint8 time)
It sets PTIMER value.
uint8 getPMAGICR (void)
It gets PMAGICR value.
void setPMAGICR (uint8 magic)
It sets PTIMER value.
uint16 getPSIDR (void)
It gets PSIDR value.
void getPDHAR (uint8 *addr)
It gets the PPPoE server hardware address.
void getUIPR (uint8 *addr)
It gets the unreachable destination IP address of ICMP message.
uint16 getUPORTR (void)
It gets the unreachable destination port number of ICMP message.
uint16 getFMTUR (void)
It gets the fragmented MTU value of ICMP message.
uint8 getPn_BRDYR (uint8 p)
It gets Pn_BRDYR value.
void setPn_BRDYR (uint8 p, uint8 cfg)
It sets Pn_BRDYR value.
uint16 getPn_BDPTHR (uint8 p)
It gets the buffer depth of PIN "BRDYn".
void setPn_BDPTHR (uint8 p, uint16 depth)
It sets the buffer depth of PIN "BRDYn".
uint16 getIDR (void)
It gets the ID of W5300.
uint16 getSn_MR (SOCKET s)
It gets Sn_MR value.
void setSn_MR (SOCKET s, uint16 mode)
It sets Sn_MR value.
uint8 getSn_CR (SOCKET s)
It gets Sn_CR value.
void setSn_CR (SOCKET s, uint16 com)
It sets Sn_CR value.
uint8 getSn_IMR (SOCKET s)
It gets Sn_IMR value.
void setSn_IMR (SOCKET s, uint8 mask)
It sets Sn_IMR value.
uint8 getSn_IR (SOCKET s)
It gets Sn_IR value.
void setSn_IR (SOCKET s, uint8 ir)
It sets Sn_IR value.
uint8 getSn_SSR (SOCKET s)
It gets Sn_SSR value.
void getSn_DHAR (SOCKET s, uint8 *addr)
It gets Sn_DHAR value.
void setSn_DHAR (SOCKET s, uint8 *addr)
It sets Sn_DHAR value.
void setSn_DPORTR (SOCKET s, uint16 port)
It sets Sn_DPORTR value.
void getSn_DIPR (SOCKET s, uint8 *addr)
It gets Sn_DIPR value.
void setSn_DIPR (SOCKET s, uint8 *addr)
It sets Sn_DIPR value.
uint16 getSn_MSSR (SOCKET s)
It gets Sn_MSSR value.
void setSn_MSSR (SOCKET s, uint16 mss)
It sets Sn_MSSR value.
uint8 getSn_KPALVTR (SOCKET s)
It gets Sn_KPALVTR value.
void setSn_KPALVTR (SOCKET s, uint8 time)
It sets Sn_KPALVTR value.
uint32 getSn_TX_WRSR (SOCKET s)
It gets Sn_TX_WRSR value.
void setSn_TX_WRSR (SOCKET s, uint32 size)
It gets Sn_KPALVTR value.
uint32 getSn_TX_FSR (SOCKET s)
It gets Sn_TX_FSR value.
uint32 getSn_RX_RSR (SOCKET s)
It gets Sn_RX_RSR value.
void setSn_TX_FIFOR (SOCKET s, uint16 data)
It sets Sn_TX_FIFOR value.
uint16 getSn_RX_FIFOR (SOCKET s)
It gets Sn_RX_FIFOR value.
uint8 getSn_PROTOR (SOCKET s)
It gets Sn_PROTOR value.
void setSn_PROTOR (SOCKET s, uint8 pronum)
It sets Sn_PROTOR value.
uint8 getSn_TOSR (SOCKET s)
It gets Sn_TOSR value.
void setSn_TOSR (SOCKET s, uint8 tos)
It sets Sn_TOSR value.
uint8 getSn_TTLR (SOCKET s)
It gets Sn_TTLR value.
void setSn_TTLR (SOCKET s, uint8 ttl)
It sets Sn_TTLR value.
uint8 getSn_FRAGR (SOCKET s)
It gets Sn_FRAGR value.
void setSn_FRAGR (SOCKET s, uint8 frag)
It sets Sn_FRAGR value.
void iinchip_init (void)
It initializes W5300.
void iinchip_irq (void)
It handles the interrupt of W5300.
uint8 sysinit (uint8 *tx_size, uint8 *rx_size)
It allocate internal TX/RX memory of each SOCKET.
uint32 wiz_write_buf (SOCKET s, uint8 *buf, uint32 len)
It copies data to interna1 TX memory.
uint32 wiz_read_buf (SOCKET s, uint8 *buf, uint32 len)
It copies data to your buffer from internal RX memory.
uint32 getIINCHIP_TxMAX (SOCKET s)
It gets the max size of internal TX memory of each SOCKET.
uint32 getIINCHIP_RxMAX (SOCKET s)
It gets the max size of internal RX memory of each SOCKET.
uint8 pppinit_in (uint8 *id, uint8 idlen, uint8 *passwd, uint8 passwdlen)
Internal function.
uint8 pppinit (uint8 *id, uint8 idlen, uint8 *passwd, uint8 passwdlen)
It initializes to PPPoE of W5300.
void pppterm (uint8 *mac, uint16 sessionid)
It terminates PPPoE connection.
void wait_1us (uint32 us)
Delay function Refer to wait_10ms().
void wait_1ms (uint32 ms)
Delay function Refer to wait_10ms().
void wait_10ms (uint32 ms)
Delay function.
Variables
uint32 TXMEM_SIZE [MAX_SOCK_NUM]
TX memory size variables.
uint32 RXMEM_SIZE [MAX_SOCK_NUM]
RX memory size variables.
uint8 SOCK_INT [MAX_SOCK_NUM]
The variables for SOCKETn interrupt.
Define Documentation
#define PPP_OPTION_BUF_LEN 64
Max lenght of PPPoE message
Definition at line 800 of file w5300.c.
Referenced by pppinit_in().
Function Documentation
uint16 getFMTUR (void)
It gets the fragmented MTU value of ICMP message.
Returns:
The fragmented MTU value
See also:
IR_FMTU, Sn_MSSR, setSn_MSSR()
Definition at line 245 of file w5300.c.
References FMTUR, and IINCHIP_READ().
void getGAR (uint8 * addr)
It gets the gateway IP address.
Parameters:
[out] addr Storage location for input the gateway IP address. It should be allocated 4bytes size.
See also:
setGAR()
Definition at line 130 of file w5300.c.
References GAR, and IINCHIP_READ().
Referenced by Main().
uint16 getIDR (void)
It gets the ID of W5300.
Returns:
0x5300
Definition at line 274 of file w5300.c.
References IDR, and IINCHIP_READ().
uint32 getIINCHIP_RxMAX (SOCKET s)
It gets the max size of internal RX memory of each SOCKET.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
It returns RXMEM_SIZE value of s-th SOCKET
Definition at line 788 of file w5300.c.
References RXMEM_SIZE.
uint32 getIINCHIP_TxMAX (SOCKET s)
It gets the max size of internal TX memory of each SOCKET.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
It returns TXMEM_SIZE value of s-th SOCKET
Definition at line 783 of file w5300.c.
References TXMEM_SIZE.
Referenced by close(), send(), and sendto().
uint16 getIMR (void)
It gets IMR value.
Returns:
The IMR value
See also:
setIMR()
Definition at line 102 of file w5300.c.
References IINCHIP_READ(), and IMR.
uint16 getIR (void)
It gets IR value.
Returns:
The IR value
See also:
setIR()
Definition at line 93 of file w5300.c.
References IINCHIP_READ(), and IR.
uint16 getMR (void)
It gets MR value.
Returns:
The value of MR
See also:
setMR()
Definition at line 77 of file w5300.c.
References MR.
Referenced by pppinit(), and pppterm().
uint16 getPATR (void)
It gets PATR value.
Returns:
The value of PATR.
If PAP it returns 0xC023.
If CHAP it returns 0xC223.
Definition at line 191 of file w5300.c.
References IINCHIP_READ(), and PATR.
Referenced by pppinit_in().
void getPDHAR (uint8 * addr)
It gets the PPPoE server hardware address.
Parameters:
[out] addr Storage location for input the source IP address. It should be allocated 6bytes size.
Definition at line 219 of file w5300.c.
References IINCHIP_READ(), and PDHAR.
Referenced by Main().
uint8 getPMAGICR (void)
It gets PMAGICR value.
Returns:
The value of PMAGICR.
See also:
setPMAGICR()
Definition at line 205 of file w5300.c.
References IINCHIP_READ(), and PMAGICR.
uint16 getPn_BDPTHR (uint8 p)
It gets the buffer depth of PIN "BRDYn".
Parameters:
[in] p The number of PIN "BRDYn". It is valid when 0 <= p <= 3.
Returns:
The buffer depth of PIN "BRDYn".
See also:
setPn_BDPTHR(), Pn_BRDYR
Definition at line 263 of file w5300.c.
References IINCHIP_READ(), and Pn_BDPTHR.
uint8 getPn_BRDYR (uint8 p)
It gets Pn_BRDYR value.
Parameters:
[in] p The number of PIN "BRDYn". It is valid when 0 <= p <= 3.
Returns:
The configuration value of Pn_BRDYR.
See also:
setPn_BRDYR(), Pn_BDPTHR
Definition at line 253 of file w5300.c.
References IINCHIP_READ(), and Pn_BRDYR.
uint16 getPSIDR (void)
It gets PSIDR value.
Returns:
The value of PSIDR.
Note:
PSIDR is read-only register.
However, in order to set PPP session ID(PSIDR), You can do it by writing S0_DPORTR to PPP session ID.
Definition at line 214 of file w5300.c.
References IINCHIP_READ(), and PSIDR.
Referenced by Main().
uint8 getPTIMER (void)
It gets PTIMER value.
Returns:
The value of PTIMER. The unit is 25ms.
See also:
setPTIMER()
Definition at line 196 of file w5300.c.
References IINCHIP_READ(), and PTIMER.
uint8 getRCR (void)
It gets RCR value.
Returns:
The value of RCR
See also:
setRCR()
Definition at line 181 of file w5300.c.
References IINCHIP_READ(), and RCR.
uint16 getRTR (void)
It gets RTR value.
Returns:
The value of RTR. The unit is 100us.
See also:
setRTR()
Definition at line 172 of file w5300.c.
References IINCHIP_READ(), and RTR.
void getSHAR (uint8 * addr)
It gets the source hardware address.
Parameters:
[out] addr Storage location for input the source hardware address. It should be allocated 6bytes size.
See also:
setSHAR()
Definition at line 114 of file w5300.c.
References IINCHIP_READ(), and SHAR.
Referenced by Main().
void getSIPR (uint8 * addr)
It gets the source IP address.
Parameters:
[out] addr Storage location for input the source IP address. It should be allocated 4bytes size.
See also:
setSIPR()
Definition at line 156 of file w5300.c.
References IINCHIP_READ(), and SIPR.
Referenced by Main().
uint8 getSn_CR (SOCKET s)
It gets Sn_CR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The command value of s-th SOCKET.
See also:
setSn_CR()
Definition at line 295 of file w5300.c.
References IINCHIP_READ(), and Sn_CR.
void getSn_DHAR (SOCKET s, uint8 * addr)
It gets Sn_DHAR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[out] addr Storage location for input the destination hardware address of s-th SOCKET. It should be allocated 6bytes size.
Note:
It is also used when you get the PPPoE server hardware address.
Refer to getPDHAR(), PDHAR
See also:
setSn_DHAR()
Definition at line 348 of file w5300.c.
References IINCHIP_READ(), and Sn_DHAR.
void getSn_DIPR (SOCKET s, uint8 * addr)
It gets Sn_DIPR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[out] addr Storage location for input the destination IP address of s-th SOCKET. It should be allocated 4bytes size.
See also:
setSn_DIPR()
Definition at line 377 of file w5300.c.
References IINCHIP_READ(), and Sn_DIPR.
uint8 getSn_FRAGR (SOCKET s)
It gets Sn_FRAGR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The Sn_FRAGR value of s-th SOCKET.
See also:
setSn_FRAGR()
Definition at line 501 of file w5300.c.
References IINCHIP_READ(), and Sn_FRAGR.
uint8 getSn_IMR (SOCKET s)
It gets Sn_IMR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The interrupt mask value of s-th SOCKET.
See also:
setSn_IMR(), Sn_IR, IR_SnINT
Definition at line 305 of file w5300.c.
References IINCHIP_READ(), and Sn_IMR.
uint8 getSn_IR (SOCKET s)
It gets Sn_IR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The interrupt status of s-th SOCKET.
See also:
setSn_IR(), Sn_IMR, IR_SnINT
Definition at line 314 of file w5300.c.
References IINCHIP_READ(), Sn_IR, and SOCK_INT.
Referenced by loopback_tcpc(), loopback_tcps(), pppinit(), pppinit_in(), pppterm(), recv(), send(), and sendto().
uint8 getSn_KPALVTR (SOCKET s)
It gets Sn_KPALVTR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The Sn_KPALVTR value of s-th SOCKET to be set.
See also:
setSn_KPALVTR()
Definition at line 405 of file w5300.c.
References IINCHIP_READ(), and Sn_KPALVTR.
uint16 getSn_MR (SOCKET s)
It gets Sn_MR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The mode value of s-th SOCKET.
See also:
setSn_MR()
Definition at line 286 of file w5300.c.
References IINCHIP_READ(), and Sn_MR.
Referenced by close().
uint16 getSn_MSSR (SOCKET s)
It gets Sn_MSSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The value of Sn_MSSR
See also:
setSn_MSSR()
Definition at line 392 of file w5300.c.
References IINCHIP_READ(), and Sn_MSSR.
uint8 getSn_PROTOR (SOCKET s)
It gets Sn_PROTOR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The protocol number of s-th SOCKET.
See also:
setSn_PROTOR()
Definition at line 472 of file w5300.c.
References IINCHIP_READ(), and Sn_PROTOR.
uint16 getSn_RX_FIFOR (SOCKET s)
It gets Sn_RX_FIFOR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The data value to be read from internal RX memory of of s-th SOCKET, through Sn_RX_FIFOR.
Definition at line 464 of file w5300.c.
References IINCHIP_READ(), and Sn_RX_FIFOR.
uint32 getSn_RX_RSR (SOCKET s)
It gets Sn_RX_RSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
It returns the byte size of received data in internal RX memory of s-th SOCKET.
Warning:
Warning:
The host can read the wrong value of Sn_RX_RSR.
Because Sn_TX_RSR is not changed by 'system bus signal' but changed by synchronous 'NIC_CLK' clock.
To prevented this problem, the host should read it until the previous value is equal to the curruent.
Definition at line 444 of file w5300.c.
References IINCHIP_READ(), and Sn_RX_RSR.
Referenced by loopback_tcpc(), loopback_tcps(), loopback_udp(), pppinit_in(), and recv().
uint8 getSn_SSR (SOCKET s)
It gets Sn_SSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The status value of s-th SOCKET.
Warning:
Warning:
The host can read the wrong value of Sn_SSR.
Because Sn_SSR is not changed by 'system bus signal' but changed by synchronous 'NIC_CLK' clock.
To prevented this problem, the host should read it until the previous value is equal to the curruent.
Definition at line 334 of file w5300.c.
References IINCHIP_READ(), and Sn_SSR.
Referenced by listen(), loopback_tcpc(), loopback_tcps(), loopback_udp(), pppterm(), send(), sendto(), and socket().
uint8 getSn_TOSR (SOCKET s)
It gets Sn_TOSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The TOS value of s-th SOCKET.
See also:
setSn_TOSR()
Definition at line 483 of file w5300.c.
References IINCHIP_READ(), and Sn_TOSR.
uint8 getSn_TTLR (SOCKET s)
It gets Sn_TTLR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The TTL value of s-th SOCKET.
See also:
setSn_TTLR()
Definition at line 492 of file w5300.c.
References IINCHIP_READ(), and Sn_TTLR.
uint32 getSn_TX_FSR (SOCKET s)
It gets Sn_TX_FSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
It returns the free size of internal TX memory(the byte size of transmittable data) of s-th SOCKET.
Warning:
Warning:
The host can read the wrong value of Sn_TX_FSR.
Because Sn_TX_FSR is not changed by 'system bus signal' but changed by synchronous 'NIC_CLK' clock.
To prevented this problem, the host should read it until the previous value is equal to the curruent.
Definition at line 430 of file w5300.c.
References IINCHIP_READ(), and Sn_TX_FSR.
Referenced by close(), and send().
uint32 getSn_TX_WRSR (SOCKET s)
It gets Sn_TX_WRSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
Returns:
The byte size of data written in internal TX memory of s-th SOCKET.
See also:
setSn_TX_WRSR()
Definition at line 417 of file w5300.c.
References IINCHIP_READ(), and Sn_TX_WRSR.
void getSUBR (uint8 * addr)
It gets the subnet mask address.
Parameters:
[out] addr Storage location for input the subnet mask address. It should be allocated 4bytes size.
See also:
getSUBR()
Definition at line 143 of file w5300.c.
References IINCHIP_READ(), and SUBR.
Referenced by Main().
void getUIPR (uint8 * addr)
It gets the unreachable destination IP address of ICMP message.
Parameters:
[out] addr Storage location for input the unreachable destination IP address. It should be allocated 4bytes size.
Note:
PDHAR is read-only register.
However, in order to set PPPoE server hardware address(PDHAR), You can do it by writing S0_DHAR to PPPoe server hardware address.
See also:
getUPORTR(), IR_DPUR
Definition at line 232 of file w5300.c.
References IINCHIP_READ(), and UIPR.
uint16 getUPORTR (void)
It gets the unreachable destination port number of ICMP message.
Returns:
The unreachable destination port number
See also:
getUIPR(), IR_DPUR
Definition at line 240 of file w5300.c.
References IINCHIP_READ(), and UPORTR.
void iinchip_init (void)
It initializes W5300.
It initializes W5300 by soft reset and decides the host interface mode by configuration MR.
Note:
You can modify this function to configure MR_WDF, MR_RDH, MR_FS, MR_DBS, MR_PB, MR_PPPoE.
Definition at line 518 of file w5300.c.
References MR, MR_IND, MR_RST, and wait_10ms().
Referenced by Main().
void iinchip_irq (void)
It handles the interrupt of W5300.
Todo:
You should do implement your interrupt request routine instead of this function. If you want to use ISR, this function should be mapped in your ISR handler.
Definition at line 536 of file w5300.c.
References IINCHIP_CRITICAL_SECTION_ENTER, IINCHIP_CRITICAL_SECTION_EXIT, IINCHIP_READ(), IINCHIP_WRITE(), IR, IR_DPUR, IR_IPCF, IR_SnINT, MAX_SOCK_NUM, Sn_IR, SOCK_INT, UIPR, and UPORTR.
uint16 IINCHIP_READ (uint32 addr)
Basic I/O function.
It reads a value from a register
Parameters:
[in] addr register address
Returns:
the value of register
Note:
If you define __DEF_IINCHIP_DIRECT_MODE__, you can use the below code instead of this function for the better performance.
 #define IINCHIP_READ(uint32 addr) (*(vint16*)addr)
Definition at line 52 of file w5300.c.
References IDM_AR, IDM_DR, IINCHIP_CRITICAL_SECTION_ENTER, and IINCHIP_CRITICAL_SECTION_EXIT.
Referenced by getFMTUR(), getGAR(), getIDR(), getIMR(), getIR(), getPATR(), getPDHAR(), getPMAGICR(), getPn_BDPTHR(), getPn_BRDYR(), getPSIDR(), getPTIMER(), getRCR(), getRTR(), getSHAR(), getSIPR(), getSn_CR(), getSn_DHAR(), getSn_DIPR(), getSn_FRAGR(), getSn_IMR(), getSn_IR(), getSn_KPALVTR(), getSn_MR(), getSn_MSSR(), getSn_PROTOR(), getSn_RX_FIFOR(), getSn_RX_RSR(), getSn_SSR(), getSn_TOSR(), getSn_TTLR(), getSn_TX_FSR(), getSn_TX_WRSR(), getSUBR(), getUIPR(), getUPORTR(), iinchip_irq(), recv(), recvfrom(), setSn_CR(), setSn_KPALVTR(), setSn_PROTOR(), socket(), sysinit(), and wiz_read_buf().
void IINCHIP_WRITE (uint32 addr, uint16 data)
Basic I/O function.
It writes a value to a register
Parameters:
[in] addr register address
[in] data write data
Returns:
void
Note:
If you define __DEF_IINCHIP_DIRECT_MODE__, you can use the below code instead of this function for the better performance.
 #define IINCHIP_WRITE(uint32 addr,uint16 data)  ((*(vint16*)addr) = data)
Definition at line 65 of file w5300.c.
References IDM_AR, IDM_DR, IINCHIP_CRITICAL_SECTION_ENTER, and IINCHIP_CRITICAL_SECTION_EXIT.
Referenced by connect(), iinchip_irq(), recv(), sendto(), setGAR(), setIMR(), setIR(), setPMAGICR(), setPn_BDPTHR(), setPn_BRDYR(), setPTIMER(), setRCR(), setRTR(), setSHAR(), setSIPR(), setSn_CR(), setSn_DHAR(), setSn_DIPR(), setSn_DPORTR(), setSn_FRAGR(), setSn_IMR(), setSn_IR(), setSn_KPALVTR(), setSn_MR(), setSn_MSSR(), setSn_PROTOR(), setSn_TOSR(), setSn_TTLR(), setSn_TX_FIFOR(), setSn_TX_WRSR(), setSUBR(), socket(), sysinit(), and wiz_write_buf().
uint8 pppinit (uint8 * id, uint8 idlen, uint8 * passwd, uint8 passwdlen)
It initializes to PPPoE of W5300.
It initiazes W5300 for PPPoE and calls pppinit_in() for PPPoE processing phase.
For the detail, refer to "How to use PPPoE in W5300".
Parameters:
[in] id User ID for connecting to a PPPoE server
[in] idlen Length of id
[in] passwd User password for connecting to a PPPoE server
[in] passwdlen Length of passwd
Returns:
It returns the result of pppinit_in()
Definition at line 1116 of file w5300.c.
References getMR(), getSn_IR(), MR_FS, MR_PPPoE, pppinit_in(), setMR(), setPMAGICR(), setPTIMER(), setSn_CR(), setSn_IR(), setSn_MR(), Sn_CR_CLOSE, Sn_CR_OPEN, and Sn_MR_PPPoE.
Referenced by Main().
uint8 pppinit_in (uint8 * id, uint8 idlen, uint8 * passwd, uint8 passwdlen)
Internal function.
It is called in pppinit().
It processes 4 phases as following.
PPPoE Discovery
LCP process
PPPoE authentication
IPCP process
Parameters:
id User ID for connecting to a PPPoE server
idlen Length of id
passwd User password for connecting to a PPPoE server
passwdlen Length of passwd
Returns:
1 - success
2 - ID or password error
3 - Timeout occurs while processing PPPoE
4 - Not support authentication type.
Definition at line 821 of file w5300.c.
References getPATR(), getSn_IR(), getSn_RX_RSR(), PPP_OPTION_BUF_LEN, setSn_CR(), setSn_IR(), setSn_TX_WRSR(), Sn_CR_PCJ, Sn_CR_PCON, Sn_CR_PCR, Sn_CR_RECV, Sn_IR_PFAIL, Sn_IR_PNEXT, Sn_IR_PRECV, wait_10ms(), wiz_read_buf(), and wiz_write_buf().
Referenced by pppinit().
void pppterm (uint8 * mac, uint16 sessionid)
It terminates PPPoE connection.
For the detail, refer to "How to use PPPoE in W5300".
Parameters:
[in] mac PPPoE server hardware address occupied by pppinit() or your PPPoE-process code.
[in] sessionid session ID occupied by pppinit() or your PPPoE-process code.
Definition at line 1143 of file w5300.c.
References getMR(), getSn_IR(), getSn_SSR(), MR_PPPoE, setMR(), setSn_CR(), setSn_DHAR(), setSn_DPORTR(), setSn_IR(), setSn_MR(), Sn_CR_CLOSE, Sn_CR_OPEN, Sn_CR_PDISCON, Sn_MR_PPPoE, SOCK_PPPoE, and wait_10ms().
Referenced by Main().
void setGAR (uint8 * addr)
It sets the gateway IP address.
Parameters:
[in] addr Pointer to the gateway IP address to be set
See also:
getGAR()
Definition at line 137 of file w5300.c.
References GAR, and IINCHIP_WRITE().
Referenced by Main().
void setIMR (uint16 mask)
It sets IMR value.
Parameters:
[in] mask The mask value to be set
See also:
getIMR()
Definition at line 106 of file w5300.c.
References IINCHIP_WRITE(), and IMR.
void setIR (uint16 val)
It sets IR value.
Parameters:
[in] val The value to be set
See also:
getIR()
Definition at line 97 of file w5300.c.
References IINCHIP_WRITE(), and IR.
void setMR (uint16 val)
It sets MR value.
Parameters:
[in] val The value to be set
See also:
getMR()
Definition at line 81 of file w5300.c.
References MR.
Referenced by pppinit(), and pppterm().
void setPMAGICR (uint8 magic)
It sets PTIMER value.
Parameters:
[in] magic The byte of 4byts MAGIC number for PPPoE
See also:
getPMAGICR()
Definition at line 209 of file w5300.c.
References IINCHIP_WRITE(), and PMAGICR.
Referenced by pppinit().
void setPn_BDPTHR (uint8 p, uint16 depth)
It sets the buffer depth of PIN "BRDYn".
Parameters:
[in] p The number of PIN "BRDYn". It is valid when 0 <= p <= 3.
[in] depth The buffer depth of PIN "BRDYn" to be set.
See also:
getPn_BDPTHR(), Pn_BRDYR
Definition at line 267 of file w5300.c.
References IINCHIP_WRITE(), and Pn_BDPTHR.
void setPn_BRDYR (uint8 p, uint8 cfg)
It sets Pn_BRDYR value.
Parameters:
[in] p The number of PIN "BRDYn". It is valid when 0 <= p <= 3.
[in] cfg The configuration values of Pn_BRDYR to be set.
See also:
getPn_BRDYR(), Pn_BDPTHR
Definition at line 257 of file w5300.c.
References IINCHIP_WRITE(), and Pn_BRDYR.
void setPTIMER (uint8 time)
It sets PTIMER value.
Parameters:
[in] time LCP echo-request transmittion timer value to be set. The unit is 25ms.
See also:
getPTIMER()
Definition at line 200 of file w5300.c.
References IINCHIP_WRITE(), and PTIMER.
Referenced by pppinit().
void setRCR (uint8 retry)
It sets RCR value.
Parameters:
[in] retry The retry count of retransmittion to be set.
See also:
getRCR()
Definition at line 185 of file w5300.c.
References IINCHIP_WRITE(), and RCR.
void setRTR (uint16 timeout)
It sets RTR value.
Parameters:
[in] timeout The timeout value to be set. The unit is 100us.
See also:
getRTR()
Definition at line 176 of file w5300.c.
References IINCHIP_WRITE(), and RTR.
void setSHAR (uint8 * addr)
It sets the source hardware address.
Parameters:
[in] addr Pointer to the source hardware address to be set.
See also:
getSHAR()
Definition at line 123 of file w5300.c.
References IINCHIP_WRITE(), and SHAR.
Referenced by Main().
void setSIPR (uint8 * addr)
It sets the source IP address.
Parameters:
[in] addr Pointer to the source IP address to be set
See also:
getSIR()
Definition at line 163 of file w5300.c.
References IINCHIP_WRITE(), and SIPR.
Referenced by Main().
void setSn_CR (SOCKET s, uint16 com)
It sets Sn_CR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] com The command value of s-th SOCKET.
Note:
It is blocked until Sn_CR is cleared.
See also:
getSn_CR()
Definition at line 299 of file w5300.c.
References IINCHIP_READ(), IINCHIP_WRITE(), and Sn_CR.
Referenced by close(), connect(), disconnect(), listen(), pppinit(), pppinit_in(), pppterm(), recv(), recvfrom(), send(), sendto(), and socket().
void setSn_DHAR (SOCKET s, uint8 * addr)
It sets Sn_DHAR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] addr Pointer to the destination hardware address of s-th SOCKET to be set.
Note:
It is also used when you set PPPoE server hardware address.
Refer to PDHAR
See also:
getSn_DHAR()
Definition at line 358 of file w5300.c.
References IINCHIP_WRITE(), and Sn_DHAR.
Referenced by pppterm().
void setSn_DIPR (SOCKET s, uint8 * addr)
It sets Sn_DIPR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] addr Pointer to the destination IP address of s-th SOCKET to be set.
See also:
getSn_DIPR()
Definition at line 386 of file w5300.c.
References IINCHIP_WRITE(), and Sn_DIPR.
void setSn_DPORTR (SOCKET s, uint16 port)
It sets Sn_DPORTR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] port The desintinaton port number of s-th SOCKET
Note:
It is also used when you set the PPP session ID.
Refer to PSIDR
Definition at line 372 of file w5300.c.
References IINCHIP_WRITE(), and Sn_DPORTR.
Referenced by pppterm().
void setSn_FRAGR (SOCKET s, uint8 frag)
It sets Sn_FRAGR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] frag The Sn_FRAGR value of s-th SOCKET to be set.
Note:
W5300 doesn't support the packet fragment at the IP layer.
Even though Sn_FRAGR is configured, IP data is not fragmented.
See also:
getSn_FRAGR()
Definition at line 506 of file w5300.c.
References IINCHIP_WRITE(), and Sn_FRAGR.
void setSn_IMR (SOCKET s, uint8 mask)
It sets Sn_IMR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] mask The interrupt mask value of s-th SOCKET.
See also:
getSn_IMR(), Sn_IR, IR_SnINT
Definition at line 309 of file w5300.c.
References IINCHIP_WRITE(), and Sn_IMR.
void setSn_IR (SOCKET s, uint8 ir)
It sets Sn_IR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] ir The interrupt status of s-th SOCKET to be cleared.
See also:
getSn_IR(), Sn_IMR, IR_SnINT
Definition at line 322 of file w5300.c.
References IINCHIP_WRITE(), Sn_IR, and SOCK_INT.
Referenced by close(), loopback_tcpc(), loopback_tcps(), pppinit(), pppinit_in(), pppterm(), recv(), send(), and sendto().
void setSn_KPALVTR (SOCKET s, uint8 time)
It sets Sn_KPALVTR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] time The keep alive timer value of s-th SOCKET to be set. The unit is 5 seconds.
Note:
When Sn_KPALVTR > 0, KEEP ALIVE(KA) packet is automatically transmitted and Sn_CR_SEND_KEEP is ignored.
When Sn_KPALVTR = 0, KA packet is manually transmitted by Sn_CR_SEND_KEEP.
See also:
getSn_KPALVTR()
Definition at line 410 of file w5300.c.
References IINCHIP_READ(), IINCHIP_WRITE(), and Sn_KPALVTR.
void setSn_MR (SOCKET s, uint16 mode)
It sets Sn_MR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] mode The mode value of s-th SOCKETn.
See also:
getSn_MR()
Definition at line 290 of file w5300.c.
References IINCHIP_WRITE(), and Sn_MR.
Referenced by pppinit(), and pppterm().
void setSn_MSSR (SOCKET s, uint16 mss)
It sets Sn_MSSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] mss The MSS value of s-th SOCKET to be set.
Note:
When receiving the fragment MTU of ICMP message at UDP mode, You should be set Sn_MSSR to FMTUR by using this function.
Refer to FMTUR, IR_FMTU.
See also:
getSn_MSSR()
Definition at line 397 of file w5300.c.
References IINCHIP_WRITE(), and Sn_MSSR.
void setSn_PROTOR (SOCKET s, uint8 pronum)
It sets Sn_PROTOR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] pronum The protocol number of s-th SOCKET to be set. pronum does't support both 0x06(TCP) and 0x11(UDP) number.
See also:
getSn_PROTOR()
Definition at line 476 of file w5300.c.
References IINCHIP_READ(), IINCHIP_WRITE(), and Sn_PROTOR.
void setSn_TOSR (SOCKET s, uint8 tos)
It sets Sn_TOSR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] tos The TOS value of s-th SOCKET to be set.
See also:
getSn_TOSR()
Definition at line 487 of file w5300.c.
References IINCHIP_WRITE(), and Sn_TOSR.
void setSn_TTLR (SOCKET s, uint8 ttl)
It sets Sn_TTLR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] ttl The TTL value of s-th SOCKET to be set.
See also:
getSn_TTLR()
Definition at line 496 of file w5300.c.
References IINCHIP_WRITE(), and Sn_TTLR.
void setSn_TX_FIFOR (SOCKET s, uint16 data)
It sets Sn_TX_FIFOR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
data The data value to be written into internal TX memory of of s-th SOCKET, through Sn_TX_FIFOR.
Definition at line 459 of file w5300.c.
References IINCHIP_WRITE(), and Sn_TX_FIFOR.
void setSn_TX_WRSR (SOCKET s, uint32 size)
It gets Sn_KPALVTR value.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] size The byte size of data written in interanl TX memory of s-th SOCKET.
See also:
getSn_TX_WRSR()
Definition at line 424 of file w5300.c.
References IINCHIP_WRITE(), and Sn_TX_WRSR.
Referenced by pppinit_in(), recv(), send(), and sendto().
void setSUBR (uint8 * addr)
It sets the subnet mask address.
Parameters:
[in] addr Pointer to the subnet mask address to be set
See also:
setSUBR()
Definition at line 150 of file w5300.c.
References IINCHIP_WRITE(), and SUBR.
Referenced by Main().
uint8 sysinit (uint8 * tx_size, uint8 * rx_size)
It allocate internal TX/RX memory of each SOCKET.
Parameters:
[in] tx_size The pointer to allocate tx_size[n] to the internal TX memory of each SOCKET.
(0 <= n <= MAX_SOCK_NUM-1).
TX memory size of each SOCKET is configurable in the range of 0~64Kbytes. Total memory size of each SOCKET's TX memory should be the multiple of 8.
[in] rx_size The pointer to allocate rx_size[n] to the internal RX memory of each SOCKET.
(0 <= n <= MAX_SOCK_NUM-1).
RX memory size of each SOCKET is configurable in the range of 0~64Kbytes. Total memory size of each SOCKET's TX memory and RX memory should be 128Kbytes.
Returns:
If success, it returns 1. Otherwize 0.
Definition at line 577 of file w5300.c.
References IINCHIP_READ(), IINCHIP_WRITE(), MAX_SOCK_NUM, MTYPER, RMS01R, RMS23R, RMS45R, RMS67R, RXMEM_SIZE, TMS01R, TMS23R, TMS45R, TMS67R, and TXMEM_SIZE.
Referenced by Main().
void wait_10ms (uint32 ms)
Delay function.
Parameters:
[in] ms - wait time It waits for the ms time.
Todo:
These delay functions depend on the MCU. Therefore, These function should be replaced with yours.
Definition at line 1200 of file w5300.c.
References wait_1ms().
Referenced by close(), iinchip_init(), pppinit_in(), and pppterm().
uint32 wiz_read_buf (SOCKET s, uint8 * buf, uint32 len)
It copies data to your buffer from internal RX memory.
It copies the len bytes of internal RX memory of s-th SOCKET to buf through Sn_RX_FIFOR.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[out] buf Destination buffer to copy
The length of buf should be equal or greater than len + 1, in order to prevent the memory violation.
[in] len bytes of internal RX memory of s-th SOCKET to copy.
Returns:
The copied byte number
Note:
In case using interrupt or multi-task, it is protected with IINCHIP_CRITICAL_SECTION_ENTER() & IINCHIP_CRITICAL_SECTION_EXIT() while Sn_RX_FIFOR read.
If no use, it can be occured some problem such as invalid PACKET_INFO or DATA.
Definition at line 714 of file w5300.c.
References IDM_AR, IDM_DR, IINCHIP_CRITICAL_SECTION_ENTER, IINCHIP_CRITICAL_SECTION_EXIT, IINCHIP_READ(), and Sn_RX_FIFOR.
Referenced by pppinit_in(), recv(), and recvfrom().
uint32 wiz_write_buf (SOCKET s, uint8 * buf, uint32 len)
It copies data to interna1 TX memory.
It copies the len bytes of buf to internal TX memory of s-th SOCKET through Sn_TX_FIFOR.
Parameters:
[in] s SOCKET number. It is valid when 0 <= s <= MAX_SOCK_NUM - 1.
[in] buf Source buffer to copy from
[in] len bytes of data to copy.
Returns:
The copied byte number
Note:
In case using interrupt or multi-task, it is protected with IINCHIP_CRITICAL_SECTION_ENTER() & IINCHIP_CRITICAL_SECTION_EXIT() while Sn_TX_FIFOR write.
If no use, it can be occured some problem such that invalid DATA are transmitted.
Definition at line 648 of file w5300.c.
References IDM_AR, IDM_DR, IINCHIP_CRITICAL_SECTION_ENTER, IINCHIP_CRITICAL_SECTION_EXIT, IINCHIP_WRITE(), and Sn_TX_FIFOR.
Referenced by pppinit_in(), send(), and sendto().
Variable Documentation
uint32 RXMEM_SIZE[MAX_SOCK_NUM]
RX memory size variables.
It stores the real allocated RX memory size of each SOCKET. Refer to RMSxyR.
Definition at line 38 of file w5300.c.
Referenced by getIINCHIP_RxMAX(), and sysinit().
uint8 SOCK_INT[MAX_SOCK_NUM]
The variables for SOCKETn interrupt.
It stores Sn_IR value when IR_SnINT(n) = '1'. (0 <= n <= MAX_SOCK_NUM-1).
Definition at line 45 of file w5300.c.
Referenced by getSn_IR(), iinchip_irq(), and setSn_IR().
uint32 TXMEM_SIZE[MAX_SOCK_NUM]
TX memory size variables.
It stores the real allocated TX memory size of each SOCKET. Refer to TMSxyR.
Definition at line 30 of file w5300.c.
Referenced by getIINCHIP_TxMAX(), and sysinit().