#!/bin/bash

./cbmc -I ../include shadow_paging_npae.c --dimacs --function shadow_get_guestentry --outfile out.dimacs; 

./qbf/multiOutputQuant.py -f out.dimacs

echo "";
./qbf/sKizzo out_ty0.qdimacs;
./qbf/sKizzo out_ty1.qdimacs;

echo "";
echo "QuBE7.1 out_ty0.qdimacs -solve ";
./qbf/QuBE7.1 out_ty0.qdimacs -solve;

echo "";
echo "QuBE7.1 out_ty1.qdimacs -solve ";
./qbf/QuBE7.1 out_ty1.qdimacs -solve;


