#!/bin/bash

echo "Preparing to start test..."
sudo insmod ./hypcall.ko
echo "Loaded hypcall kernel module"
dmesg | grep "hypcall"
echo "Executing usr mode hyper call test app..."
sudo ./apphcall
echo "usr mode hyper call test app executed"
#echo "executing usr mode npf test app..."
#sudo ./appnpf
#echo "usr mode npf test app executed"
sudo rmmod hypcall.ko
echo "Unloaded hypcall kernel module"
dmesg | grep "hypcall"
echo "All done. Shutting down..."
sudo shutdown -hP now
