
/* autogenerated XMHF hypervisor slab table data structure */
/* author: amit vasudevan (amitvasudevan.org) */
#include <xmhf.h>

extern u8 _slab_hictestslab1_code_start[];
extern u8 _slab_hictestslab1_code_end[];
extern u8 _slab_hictestslab1_rodata_start[];
extern u8 _slab_hictestslab1_rodata_end[];
extern u8 _slab_hictestslab1_rwdata_start[];
extern u8 _slab_hictestslab1_rwdata_end[];
extern u8 _slab_hictestslab1_stack_start[];
extern u8 _slab_hictestslab1_stack_end[];
extern u8 _slab_hictestslab1_entrypoint[];
extern u8 _slab_hictestslab1_entrypointnew[];

slab_header_t _slab_table[XMHF_SLAB_NUMBEROFSLABS] = {

{
	.slab_index = 0,
	.slab_macmid = 0,
	.slab_privilegemask = 0,
	.slab_tos = _slab_hictestslab1_stack_end,
	.slab_code.start = _slab_hictestslab1_code_start,
	.slab_code.end = _slab_hictestslab1_code_end,
	.slab_rodata.start = _slab_hictestslab1_rodata_start,
	.slab_rodata.end = _slab_hictestslab1_rodata_end,
	.slab_rwdata.start = _slab_hictestslab1_rwdata_start,
	.slab_rwdata.end = _slab_hictestslab1_rwdata_end,
	.slab_stack.start = _slab_hictestslab1_stack_start,
	.slab_stack.end = _slab_hictestslab1_stack_end,
	.entry_cr3 = _slab_hictestslab1_entrypoint,
	.entry_cr3_new = _slab_hictestslab1_entrypointnew,
},
};