# author: amit vasudevan (amitvasudevan@acm.org)

#external scripts
BUILD_SCRIPT = mksys.bat

# targets
.PHONY: all
all: 
	/cygdrive/c/windows/system32/cmd.exe /c "d:\project\lockdown2\ldnvnet\mksys.bat"

.PHONY: clean 
clean: 
	$(RM) -rf ./sys/objchk_wnet_x86
	$(RM) -rf ./sys/*.log
	$(RM) -rf ./sys/*.err
	 
  

  
