
/* autogenerated XMHF blue print conformance sentinel stub file */
/* author: amit vasudevan (amitvasudevan@acm.org) */

#include <xmhf.h>
#include <xmhf-debug.h>
#include <xmhfgeec.h>


#include <xc.h>
#include <geec_prime.h>


void __slab_callsentinel(slab_params_t *sp){
  /*@assert (sp->src_slabid == 1 && ( 0x0000031dUL  & (1UL << sp->dst_slabid))) ; */
}
