#top-level Makefile for rich guest app, hyperdep (rgapp-hyperdep)
# author: amit vasudevan (amitvasudevan@acm.org)

.PHONY: all
all: 
	gcc -m32 rgapp-hyperdep.c -o rgapp-hyperdep

.PHONY: clean
clean:
	rm -f rgapp-hyperdep
	rm -f *.o
	