
/* autogenerated uobj info table */
/* author: amit vasudevan (amitvasudevan@acm.org) */


#include <uberspark/uobjcoll/platform/pc/uxmhf/main/include/xmhf.h>
#include <uberspark/uobjcoll/platform/pc/uxmhf/main/include/geec.h>
#include <uberspark/uobjcoll/platform/pc/uxmhf/main/include/xmhf.h>
// #include <uberspark/uobjcoll/platform/pc/uxmhf/main/include/xmhf-debug.h>


__attribute__(( section(".data") )) __attribute__((aligned(4096))) xmhfgeec_slab_info_t xmhfgeec_slab_info_table[] = {

	//geec_sentinel
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_SENTINEL,
	        {
	            0x06800000 + (1*XMHF_SLAB_STACKSIZE),
	            0x06800000 + (2*XMHF_SLAB_STACKSIZE),
	            0x06800000 + (3*XMHF_SLAB_STACKSIZE),
	            0x06800000 + (4*XMHF_SLAB_STACKSIZE),
	            0x06800000 + (5*XMHF_SLAB_STACKSIZE),
	            0x06800000 + (6*XMHF_SLAB_STACKSIZE),
	            0x06800000 + (7*XMHF_SLAB_STACKSIZE),
	            0x06800000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000906UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
	{ .vendor_id= 0xFFFF, .device_id= 0x0000 },
}, 

0x00000001,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x06200000, .addr_end = 0x06400000, .protection = 0},
	        {.addr_start = 0x06400000, .addr_end = 0x06800000, .protection = 0},
	        {.addr_start = 0x06800000, .addr_end = 0x07200000, .protection = 0},
	        {.addr_start = 0x07200000, .addr_end = 0x07400000, .protection = 0},
	    },
	    0x06200000
	},


	//geec_prime
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x0ae00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0ae00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0ae00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0ae00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0ae00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0ae00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0ae00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0ae00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000000UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000003,
	0x00000002,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
	{ .vendor_id= 0xFFFF, .device_id= 0x0000 },
	{ .vendor_id= 0xFFFF, .device_id= 0x0002 },
	{ .vendor_id= 0xFFFF, .device_id= 0x0001 },
	{ .vendor_id= 0xFFFF, .device_id= 0x0003 },
}, 

0x00000004,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x07400000, .addr_end = 0x07600000, .protection = 0},
	        {.addr_start = 0x07600000, .addr_end = 0x0ae00000, .protection = 0},
	        {.addr_start = 0x0ae00000, .addr_end = 0x0bc00000, .protection = 0},
	        {.addr_start = 0x0bc00000, .addr_end = 0x0be00000, .protection = 0},
	    },
	    0x07400000
	},


	//xc_init
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x0c200000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0c200000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0c200000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0c200000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0c200000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0c200000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0c200000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0c200000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000002UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x0000000b,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0be00000, .addr_end = 0x0c000000, .protection = 0},
	        {.addr_start = 0x0c000000, .addr_end = 0x0c200000, .protection = 0},
	        {.addr_start = 0x0c200000, .addr_end = 0x0c800000, .protection = 0},
	        {.addr_start = 0x0c800000, .addr_end = 0x0ca00000, .protection = 0},
	    },
	    0x0be00000
	},


	//xc_exhub
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x0ce00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0ce00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0ce00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0ce00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0ce00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0ce00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0ce00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0ce00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000012UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0ca00000, .addr_end = 0x0cc00000, .protection = 0},
	        {.addr_start = 0x0cc00000, .addr_end = 0x0ce00000, .protection = 0},
	        {.addr_start = 0x0ce00000, .addr_end = 0x0d400000, .protection = 0},
	        {.addr_start = 0x0d400000, .addr_end = 0x0d600000, .protection = 0},
	    },
	    0x0ca00000
	},


	//xc_ihub
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x0da00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0da00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0da00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0da00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0da00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0da00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0da00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0da00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000002UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x0000000f,
	0x00000003,
	0x00000008,
	0x0000000c,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0d600000, .addr_end = 0x0d800000, .protection = 0},
	        {.addr_start = 0x0d800000, .addr_end = 0x0da00000, .protection = 0},
	        {.addr_start = 0x0da00000, .addr_end = 0x0e000000, .protection = 0},
	        {.addr_start = 0x0e000000, .addr_end = 0x0e200000, .protection = 0},
	    },
	    0x0d600000
	},


	//xc_nwlog
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x0e600000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0e600000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0e600000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0e600000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0e600000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0e600000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0e600000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0e600000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00001000UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0e200000, .addr_end = 0x0e400000, .protection = 0},
	        {.addr_start = 0x0e400000, .addr_end = 0x0e600000, .protection = 0},
	        {.addr_start = 0x0e600000, .addr_end = 0x0ec00000, .protection = 0},
	        {.addr_start = 0x0ec00000, .addr_end = 0x0ee00000, .protection = 0},
	    },
	    0x0e200000
	},


	//uapi_gcpustate
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x0f200000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0f200000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0f200000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0f200000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0f200000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0f200000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0f200000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0f200000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00007014UL, 
       true,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0ee00000, .addr_end = 0x0f000000, .protection = 0},
	        {.addr_start = 0x0f000000, .addr_end = 0x0f200000, .protection = 0},
	        {.addr_start = 0x0f200000, .addr_end = 0x0f800000, .protection = 0},
	        {.addr_start = 0x0f800000, .addr_end = 0x0fa00000, .protection = 0},
	    },
	    0x0ee00000
	},


	//uapi_hcpustate
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x0fe00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x0fe00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x0fe00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x0fe00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x0fe00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x0fe00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x0fe00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x0fe00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000010UL, 
       true,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x0fa00000, .addr_end = 0x0fc00000, .protection = 0},
	        {.addr_start = 0x0fc00000, .addr_end = 0x0fe00000, .protection = 0},
	        {.addr_start = 0x0fe00000, .addr_end = 0x10400000, .protection = 0},
	        {.addr_start = 0x10400000, .addr_end = 0x10600000, .protection = 0},
	    },
	    0x0fa00000
	},


	//uapi_slabmempgtbl
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x14a00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x14a00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x14a00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x14a00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x14a00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x14a00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x14a00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x14a00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00003012UL, 
       true,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x10600000, .addr_end = 0x10800000, .protection = 0},
	        {.addr_start = 0x10800000, .addr_end = 0x14a00000, .protection = 0},
	        {.addr_start = 0x14a00000, .addr_end = 0x15000000, .protection = 0},
	        {.addr_start = 0x15000000, .addr_end = 0x15200000, .protection = 0},
	    },
	    0x10600000
	},


	//uapi_sysdata
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x15600000 + (1*XMHF_SLAB_STACKSIZE),
	            0x15600000 + (2*XMHF_SLAB_STACKSIZE),
	            0x15600000 + (3*XMHF_SLAB_STACKSIZE),
	            0x15600000 + (4*XMHF_SLAB_STACKSIZE),
	            0x15600000 + (5*XMHF_SLAB_STACKSIZE),
	            0x15600000 + (6*XMHF_SLAB_STACKSIZE),
	            0x15600000 + (7*XMHF_SLAB_STACKSIZE),
	            0x15600000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000012UL, 
       true,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x15200000, .addr_end = 0x15400000, .protection = 0},
	        {.addr_start = 0x15400000, .addr_end = 0x15600000, .protection = 0},
	        {.addr_start = 0x15600000, .addr_end = 0x15c00000, .protection = 0},
	        {.addr_start = 0x15c00000, .addr_end = 0x15e00000, .protection = 0},
	    },
	    0x15200000
	},


	//uapi_iotbl
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x16200000 + (1*XMHF_SLAB_STACKSIZE),
	            0x16200000 + (2*XMHF_SLAB_STACKSIZE),
	            0x16200000 + (3*XMHF_SLAB_STACKSIZE),
	            0x16200000 + (4*XMHF_SLAB_STACKSIZE),
	            0x16200000 + (5*XMHF_SLAB_STACKSIZE),
	            0x16200000 + (6*XMHF_SLAB_STACKSIZE),
	            0x16200000 + (7*XMHF_SLAB_STACKSIZE),
	            0x16200000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000000UL, 
       true,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x15e00000, .addr_end = 0x16000000, .protection = 0},
	        {.addr_start = 0x16000000, .addr_end = 0x16200000, .protection = 0},
	        {.addr_start = 0x16200000, .addr_end = 0x16800000, .protection = 0},
	        {.addr_start = 0x16800000, .addr_end = 0x16a00000, .protection = 0},
	    },
	    0x15e00000
	},


	//uapi_uhmpgtbl
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x17600000 + (1*XMHF_SLAB_STACKSIZE),
	            0x17600000 + (2*XMHF_SLAB_STACKSIZE),
	            0x17600000 + (3*XMHF_SLAB_STACKSIZE),
	            0x17600000 + (4*XMHF_SLAB_STACKSIZE),
	            0x17600000 + (5*XMHF_SLAB_STACKSIZE),
	            0x17600000 + (6*XMHF_SLAB_STACKSIZE),
	            0x17600000 + (7*XMHF_SLAB_STACKSIZE),
	            0x17600000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000000UL, 
       true,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x16a00000, .addr_end = 0x16c00000, .protection = 0},
	        {.addr_start = 0x16c00000, .addr_end = 0x17600000, .protection = 0},
	        {.addr_start = 0x17600000, .addr_end = 0x17c00000, .protection = 0},
	        {.addr_start = 0x17c00000, .addr_end = 0x17e00000, .protection = 0},
	    },
	    0x16a00000
	},


	//xh_syscalllog
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x18200000 + (1*XMHF_SLAB_STACKSIZE),
	            0x18200000 + (2*XMHF_SLAB_STACKSIZE),
	            0x18200000 + (3*XMHF_SLAB_STACKSIZE),
	            0x18200000 + (4*XMHF_SLAB_STACKSIZE),
	            0x18200000 + (5*XMHF_SLAB_STACKSIZE),
	            0x18200000 + (6*XMHF_SLAB_STACKSIZE),
	            0x18200000 + (7*XMHF_SLAB_STACKSIZE),
	            0x18200000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000014UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000003,
	0x0000000f,
	0x00000000,
	0x0000000e,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x17e00000, .addr_end = 0x18000000, .protection = 0},
	        {.addr_start = 0x18000000, .addr_end = 0x18200000, .protection = 0},
	        {.addr_start = 0x18200000, .addr_end = 0x18800000, .protection = 0},
	        {.addr_start = 0x18800000, .addr_end = 0x18a00000, .protection = 0},
	    },
	    0x17e00000
	},


	//xh_hyperdep
	{
	    true,
	        XMHFGEEC_SLABTYPE_VfT_PROG,
	        {
	            0x18e00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x18e00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x18e00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x18e00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x18e00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x18e00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x18e00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x18e00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000014UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000005,
	0x00000000,
	0x00000006,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x18a00000, .addr_end = 0x18c00000, .protection = 0},
	        {.addr_start = 0x18c00000, .addr_end = 0x18e00000, .protection = 0},
	        {.addr_start = 0x18e00000, .addr_end = 0x19400000, .protection = 0},
	        {.addr_start = 0x19400000, .addr_end = 0x19600000, .protection = 0},
	    },
	    0x18a00000
	},


	//xh_ssteptrace
	{
	    true,
	        XMHFGEEC_SLABTYPE_uVU_PROG,
	        {
	            0x19a00000 + (1*XMHF_SLAB_STACKSIZE),
	            0x19a00000 + (2*XMHF_SLAB_STACKSIZE),
	            0x19a00000 + (3*XMHF_SLAB_STACKSIZE),
	            0x19a00000 + (4*XMHF_SLAB_STACKSIZE),
	            0x19a00000 + (5*XMHF_SLAB_STACKSIZE),
	            0x19a00000 + (6*XMHF_SLAB_STACKSIZE),
	            0x19a00000 + (7*XMHF_SLAB_STACKSIZE),
	            0x19a00000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000014UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000007,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00000000UL,
       0x00000000UL,

{ 
0 
}, 

0x00000000,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x19600000, .addr_end = 0x19800000, .protection = 0},
	        {.addr_start = 0x19800000, .addr_end = 0x19a00000, .protection = 0},
	        {.addr_start = 0x19a00000, .addr_end = 0x1a000000, .protection = 0},
	        {.addr_start = 0x1a000000, .addr_end = 0x1a200000, .protection = 0},
	    },
	    0x19600000
	},


	//xg_richguest
	{
	    true,
	        XMHFGEEC_SLABTYPE_uVU_PROG_RICHGUEST,
	        {
	            0x00000000 + (1*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (2*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (3*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (4*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (5*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (6*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (7*XMHF_SLAB_STACKSIZE),
	            0x00000000 + (8*XMHF_SLAB_STACKSIZE),
	        },
	0x00000004UL, 
       false,
       {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,

       },
       0x00005014,
       0x00005014,

{ 
	{ .vendor_id= 0xffff, .device_id= 0xffff },
}, 

0x00000001,

{ 
0 
}, 

0x00000000,
	    {
	        {.addr_start = 0x00000000, .addr_end = 0x06200000, .protection = 0},
	        {.addr_start = 0x23400000, .addr_end = 0xffffffff, .protection = 0},
	        {.addr_start = 0x00000000, .addr_end = 0x00000000, .protection = 0},
	        {.addr_start = 0x00000000, .addr_end = 0x00000000, .protection = 0},
	    },
	    0x00000000
	},

};