
/* autogenerated uberSpark uobj interuobjcoll callees info source */
/* author: amit vasudevan (amitvasudevan@acm.org) */

#include <uberspark/include/uberspark.h>
#include <uberspark/include/binformat.h>


__attribute__(( section(".uobj_interuobjcoll_cinfo_hdr") )) usbinformat_uobj_interuobjcoll_callee_info_hdr_t uobj_interuobjcoll_callee_info_hdr = {
	0x00000000UL
};
__attribute__(( section(".uobj_interuobjcoll_cinfo") )) usbinformat_uobj_callee_info_t uobj_interuobjcoll_callee_info [] = {
};

