
/* autogenerated uberSpark uobj public methods info source */
/* author: amit vasudevan (amitvasudevan@acm.org) */

#include <uberspark/include/uberspark.h>
#include <uberspark/include/binformat.h>

#include <uberspark/uobjcoll/platform/rpi3/uxmhf/main/include/uobj.h>


__attribute__(( section(".uobj_pminfo_hdr") )) usbinformat_uobj_publicmethod_info_hdr_t uobj_pminfo_hdr = {
	0x00000001UL
};
__attribute__(( section(".uobj_pminfo") )) usbinformat_uobj_publicmethod_info_t uobj_pminfo [] = {
	{
		"main",
		(uint32_t)&main,
		(uint32_t)0UL
	},
};

