
/* autogenerated uberSpark top-level include header */
/* author: amit vasudevan (amitvasudevan@acm.org) */




#ifndef __ASSEMBLY__

extern void UBERSPARK_UOBJ_PUBLICMETHOD(main) (uint32_t r0, uint32_t id, struct atag *at, uint32_t cpuid);

#endif //__ASSEMBLY__

