#top-level Makefile for rich guest app, ssteptrace (rgapp-ssteptrace)
# author: amit vasudevan (amitvasudevan@acm.org)

.PHONY: all
all: 
	gcc -m32 rgapp-ssteptrace.c -o rgapp-ssteptrace

.PHONY: clean
clean:
	rm -f rgapp-ssteptrace
	rm -f *.o
	