# test host 'creeper' (Dell PowerEdge T105 server with AMD CPU)

TEST_SLASHBOOT=/boot
TEST_HOSTNAME=creeper
TEST_MACADDR=00:22:19:27:7a:1d
TEST_CONNECTION_SERIAL_PORT=ttyS4
TEST_CONNECTION_OUTLET_NUMBER=1
