
/* autogenerated XMHF blue print conformance sentinel stub file */
/* author: amit vasudevan (amitvasudevan@acm.org) */

#include <xmhf.h>
#include <xmhf-debug.h>
#include <xmhfgeec.h>


#include <xc.h>
#include <uapi_sysdata.h>


void __slab_callsentinel(slab_params_t *sp){
  /*@assert 1 ; */
}
