#!/usr/bin/perl
# script to generate XMHF slab physical memory extents
# based on the slab names provided
# author: amit vasudevan (amitvasudevan@acm.org)

my $i = 0;

print "\n/* autogenerated XMHF slab physical memory extents */";
print "\n/* author: amit vasudevan (amitvasudevan@acm.org) */";

print "\n#include <xmhf.h>";

while( $i <= $#ARGV) {
	print "\n";
	print "\nextern u8 _slab_$ARGV[$i]_code_start[];";
	print "\nextern u8 _slab_$ARGV[$i]_code_end[];";
	print "\nextern u8 _slab_$ARGV[$i]_rwdata_start[];";
	print "\nextern u8 _slab_$ARGV[$i]_rwdata_end[];";
	print "\nextern u8 _slab_$ARGV[$i]_rodata_start[];";
	print "\nextern u8 _slab_$ARGV[$i]_rodata_end[];";
	print "\nextern u8 _slab_$ARGV[$i]_stack_start[];";
	print "\nextern u8 _slab_$ARGV[$i]_stack_end[];";
	print "\nextern u8 _slab_$ARGV[$i]_dmadata_start[];";
	print "\nextern u8 _slab_$ARGV[$i]_dmadata_end[];";
#	print "\nextern u8 _slab_$ARGV[$i]_entrypoint[];";

	$i++;
}

print "\n";
print "\nslab_physmem_extent_t _xmhfhic_init_setupdata_slab_physmem_extents[XMHF_HIC_MAX_SLABS][HIC_SLAB_PHYSMEM_MAXEXTENTS] = {";

$i = 0;
while( $i <= $#ARGV) {
	print "\n";
	print "\n{";
	print "\n	{.addr_start = _slab_$ARGV[$i]_code_start, .addr_end = _slab_$ARGV[$i]_code_end, .protection = 0},";
	print "\n	{.addr_start = _slab_$ARGV[$i]_rwdata_start, .addr_end = _slab_$ARGV[$i]_rwdata_end, .protection = 0},";
	print "\n	{.addr_start = _slab_$ARGV[$i]_rodata_start, .addr_end = _slab_$ARGV[$i]_rodata_end, .protection = 0},";
	print "\n	{.addr_start = _slab_$ARGV[$i]_stack_start, .addr_end = _slab_$ARGV[$i]_stack_end, .protection = 0},";
	print "\n	{.addr_start = _slab_$ARGV[$i]_dmadata_start, .addr_end = _slab_$ARGV[$i]_dmadata_end, .protection = 0},";
	print "\n},";

	$i++;
}

print "\n};";

exit 0;
