#!/bin/bash

cp out.dimacs last.dimacs;
cp out.qdimacs last.qdimacs;
rm out.dimacs out.qdimacs;

./cbmc -I ../include shadow_paging_npae.c --dimacs --function shadow_get_guestentry --outfile out.dimacs; 

./qbf/dimacsQuantifier.py -f out.dimacs >> out.qdimacs;

echo "";
./qbf/sKizzo out.qdimacs;

echo "";
echo "QuBE7.1 out.qdimacs -solve ";
./qbf/QuBE7.1 out.qdimacs -solve;

#echo "GhostQ output: ";
#python ./qbf/ghostq-bin/cqbf-conv.py out.qdimacs -o out.cqbf -quiet
#./qbf/ghostq out.cqbf -q1;


