#-------------------------------------------------------------------------------
# Makefile for quiesce EMHF hyperapp - guest OS control
# author: amit vasudevan (amitvasudevan@acm.org)

.PHONY: all
all:
	gcc qcontrol.c -o qcontrol
	
# cleanup
.PHONY: clean
clean: 
	rm -rf qcontrol

