FRAMAC_SHARE :=$(shell frama-c-config -print-share-path)
FRAMAC_LIBDIR :=$(shell frama-c-config -print-libpath)
PLUGIN_NAME = Uccomp
PLUGIN_CMO = umfcommon uccomp_main
include $(FRAMAC_SHARE)/Makefile.dynamic
