# makefile for xmhf-startup component
# author: amit vasudevan (amitvasudevan@acm.org)

# source files
AS_SOURCES =

C_SOURCES =  runtime.c
C_SOURCES += rntm-data.c

C_SOURCES += ./arch/x86/rntm-x86-data.c

# targets
include ../runtime.mk

