#top-level Makefile for rich guest app, syscalllog (rgapp-syscalllog)
# author: amit vasudevan (amitvasudevan@acm.org)

.PHONY: all
all: 
	gcc -m32 rgapp-syscalllog.c -o rgapp-syscalllog

.PHONY: clean
clean:
	rm -f rgapp-syscalllog
	rm -f *.o
	