# makefile for xmhf-nested (XMHF nested virtualization)
# author: Eric Li (xiaoyili@andrew.cmu.edu)

# source files
AS_SOURCES =

C_SOURCES =  ./arch/x86/vmx/nested-x86vmx-handler.c

# targets
include ../runtime.mk

