# makefile for xmhf-nested (XMHF nested virtualization)
# author: Eric Li (xiaoyili@andrew.cmu.edu)

# source files
AS_SOURCES =

C_SOURCES =  ./arch/x86/vmx/nested-x86vmx-handler1.c
C_SOURCES += ./arch/x86/vmx/nested-x86vmx-handler2.c
C_SOURCES += ./arch/x86/vmx/nested-x86vmx-vmcs12.c
C_SOURCES += ./arch/x86/vmx/nested-x86vmx-ept12.c

# targets
include ../runtime.mk

