FRAMAC_SHARE :=$(shell frama-c-config -print-share-path)
FRAMAC_LIBDIR :=$(shell frama-c-config -print-libpath)
PLUGIN_NAME = Uhwm
PLUGIN_CMO = umfcommon uhwm_main
include $(FRAMAC_SHARE)/Makefile.dynamic
