#!/usr/bin/expect -f
#
# alldone.exp
#   Connect up to a device on a serial port
#   Print a message to the port.

       # port is any serial port (omit the /dev/ prefix)
       # e.g. ttya, cua0, serialA, serialB, boca01 - boca16

# Jon found this at: http://www.aps.anl.gov/Sectors/33_34/controls/docs/serialWatch.html

if {$argc != 1} {
  puts "$argc, $argv"
  puts "usage: alldone.exp port"
  exit
}

puts "\n Log starting..."
set port /dev/$argv
set spawned [spawn -open [open $port w+]]
puts "[string trim $spawned \r\n]"
set baud 115200
    # -parenb means don't use a parity bit
    # -cstopb means "not 2 stop bits, but 1"
    # cs8 means 8 bits
    # -echo means no echo (full duplex?)
stty ispeed $baud ospeed $baud raw -echo cs8 -parenb -cstopb onlcr < $port
log_user 0

set send_slow {1 .05}
send -s "\r\nREGRESSION TESTING COMPLETED.\r\n"

