#!/usr/bin/expect -f 
# 
#   Connect up to a device on a serial port 
#   Time stamp any incoming lines to stdout

       # port is any serial port (omit the /dev/ prefix) 
       # e.g. ttya, cua0, serialA, serialB, boca01 - boca16

# Jon based this on:
# http://www.aps.anl.gov/Sectors/33_34/controls/docs/serialWatch.html

#exp_internal -f internal.log 1

if {$argc != 1} { 
  puts "$argc, $argv" 
  puts "usage: serial.exp port" 
  exit 
}

proc timeStamp {} { 
  global tcl_version 
  if {$tcl_version >= 7.5} { 
    # "clock" command requires Tcl v7.5 or greater 
    # internal routine a little faster than making a system call 
    set stamp [clock format [clock seconds] -format %Y-%m-%d,%T] 
  } else { 
    # fall back to standard UNIX system call 
    set stamp [exec /bin/date +%Y-%m-%d,%T] 
  } 
  return $stamp 
}

puts "\n[timeStamp] Log starting..." 
set port /dev/$argv 
set spawned [spawn -open [open $port w+]] 
puts "[timeStamp]: [string trim $spawned \r\n]" 
set baud 115200
    # -parenb means don't use a parity bit 
    # -cstopb means "not 2 stop bits, but 1" 
    # cs8 means 8 bits 
    # -echo means no echo (full duplex?) 
stty ispeed $baud ospeed $baud raw -echo cs8 -parenb -cstopb onlcr < $port 

set timeout 60
set send_human {.1 .3 1 .05 .5}
log_file foo.log
log_user 1

expect "Press any key to continue."
puts "ONE [string trim $expect_out(buffer) \r\n]" 
send -h "c"

expect "command-line."
puts "TWO [string trim $expect_out(buffer) \r\n]" 
send -h "c"

expect "grub>"
puts "THREE [string trim $expect_out(buffer) \n]" 
send -h "root (hd0,0)\r\n"

expect "grub>"
puts "FOUR [string trim $expect_out(buffer) \n]" 
send -h "kernel /init-x86.bin serial=115200,8n1,0x3f8\r\n"

expect "grub>"
puts "FIVE [string trim $expect_out(buffer) \n]" 
send -h "module /hypervisor-x86.bin.gz\r\n"

expect "grub>"
puts "SIX [string trim $expect_out(buffer) \n]" 
send -h "modulenounzip (hd0)+1\r\n"

expect "grub>"
puts "SEVEN [string trim $expect_out(buffer) \n]" 
send -h "module /i5_i7_DUAL_SINIT_18.BIN\r\n"

expect "grub>"
puts "EIGHT [string trim $expect_out(buffer) \n]" 
send -h "boot\r\n"

# log each input line 
#  add a timeStamp at the beginning of each line 
while {1} { 
  expect "\n" { 
    puts "[timeStamp]: [string trim $expect_out(buffer) \r\n]" 
  } 
} 

