/*
	configuration

	author: amit vasudevan (amitvasudevan@acm.org)
*/

#ifndef __CONFIG_H__
#define __CONFIG_H__


// TBD: auto-generate these compile time definitions via uobjcoll manifest
#define __UBERSPARK_UOBJCOLL_CONFIGDEF_UXMHF_CORE_START_ADDR__ 	0x01000000
#define __UBERSPARK_UOBJCOLL_CONFIGDEF_UXMHF_CORE_SIZE__			( 0x00200000 + 0x00200000 + 0x01100000)
#define __UBERSPARK_UOBJCOLL_CONFIGDEF_UXMHF_CORE_END_ADDR__ 	( __UBERSPARK_UOBJCOLL_CONFIGDEF_UXMHF_CORE_START_ADDR__ + __UBERSPARK_UOBJCOLL_CONFIGDEF_UXMHF_CORE_SIZE__)
#define __UBERSPARK_UOBJCOLL_CONFIGDEF_UXMHF_BOOT_PARTITION_START__	8192
#define __UBERSPARK_UOBJCOLL_CONFIGDEF_UXMHF_BOOT_PARTITION_END__	137215


//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_SECBOOT__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_DMAPROT__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_INTPROT__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_FIQREFLECTION__
#define __UBERSPARK_UOBJCOLL_CONFIGDEF_DEBUG_UART__
#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UART_MINI__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UART_PL011__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UART_PL011_CTSRTS__

//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UAPP_CTXTRACE__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UAPP_PA5ENCFS__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UAPP_PVDRIVER_UART__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UAPP_UAGENT__
#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UAPP_UHCALLTEST__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UAPP_UHSIGN__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UAPP_UHSTATEDB__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UAPP_UTPMTEST__
//#define __UBERSPARK_UOBJCOLL_CONFIGDEF_ENABLE_UAPP_WATCHDOG__





#ifndef __ASSEMBLY__


#endif // __ASSEMBLY__


#endif //__CONFIG_H__
