(*
	frama-c plugin for composition check
	author: amit vasudevan (amitvasudevan@acm.org)
*)
open Umfcommon

module Self = Plugin.Register
	(struct
		let name = "US composition check"
		let shortname = "ucvf"
		let help = "UberSpark composition check"
	end)


module Cmdopt_slabsfile = Self.String
	(struct
		let option_name = "-umf-uobjlist"
		let default = ""
		let arg_name = "uobjlist-file"
		let help = "uobj list file"
	end)

module Cmdopt_outputfile_ccompdriverfile = Self.String
	(struct
		let option_name = "-umf-outuobjccompdriver"
		let default = ""
		let arg_name = "outuobjccompdriver-file"
		let help = "output uobj composition check driver file"
	end)


module Cmdopt_outputfile_ccompcheckfile = Self.String
	(struct
		let option_name = "-umf-outuobjccompcheck"
		let default = ""
		let arg_name = "outuobjccompcheck-file"
		let help = "output uobj composition check file"
	end)


module Cmdopt_maxincldevlistentries = Self.String
	(struct
		let option_name = "-umf-maxincldevlistentries"
		let default = ""
		let arg_name = "max-incldevlistentries"
		let help = "total number of INCL device list entries"
	end)

module Cmdopt_maxexcldevlistentries = Self.String
	(struct
		let option_name = "-umf-maxexcldevlistentries"
		let default = ""
		let arg_name = "max-excldevlistentries"
		let help = "total number of EXCL device list entries"
	end)

module Cmdopt_maxmemoffsetentries = Self.String
	(struct
		let option_name = "-umf-maxmemoffsetentries"
		let default = ""
		let arg_name = "max-memoffsetentries"
		let help = "total number of MEMOFFSET entries"
	end)

module Cmdopt_memoffsets = Self.False
	(struct
		let option_name = "-umf-memoffsets"
		(* let default = false *)
		let help = "when on (off by default), include absolute memory offsets in MEMOFFSETS list"
	end)


(*
	**************************************************************************
	global variables
	**************************************************************************
*)

(*	command line inputs *)
let g_slabsfile = ref "";;	(* argv 0 *)
let g_outputfile_ccompdriverfile = ref "";; (* argv 1 *)
let g_outputfile_ccompcheckfile = ref "";; (* argv 2 *)
(* let g_maxincldevlistentries = ref 0;; *) (* argv 3 *)
(* let g_maxexcldevlistentries = ref 0;; *) (* argv 4 *)
(* let g_maxmemoffsetentries = ref 0;; *) (* argv 5 *)
let g_memoffsets = ref false;; (*argv 6 *)

(* other global variables *)
let g_rootdir = ref "";;



let uccomp_process_cmdline () =
	g_slabsfile := Cmdopt_slabsfile.get();
	g_outputfile_ccompdriverfile := Cmdopt_outputfile_ccompdriverfile.get();
	g_outputfile_ccompcheckfile := Cmdopt_outputfile_ccompcheckfile.get();
	g_maxincldevlistentries := int_of_string (Cmdopt_maxincldevlistentries.get());
	g_maxexcldevlistentries := int_of_string (Cmdopt_maxexcldevlistentries.get());
	g_maxmemoffsetentries := int_of_string (Cmdopt_maxmemoffsetentries.get());
	if Cmdopt_memoffsets.get() then g_memoffsets := true else g_memoffsets := false;

	
	Self.result "g_slabsfile=%s\n" !g_slabsfile;
	Self.result "g_outputfile_ccompdriverfile=%s\n" !g_outputfile_ccompdriverfile;
	Self.result "g_outputfile_ccompcheckfile=%s\n" !g_outputfile_ccompcheckfile;
	Self.result "g_maxincldevlistentries=%d\n" !g_maxincldevlistentries;
	Self.result "g_maxexcldevlistentries=%d\n" !g_maxexcldevlistentries;
	Self.result "g_maxmemoffsetentries=%d\n" !g_maxmemoffsetentries;
	Self.result "g_memoffsets=%b\n" !g_memoffsets;
	()



let uccomp_outputccompdriverfile () =


	()

(*
######
# output composition driver file
######
sub uccomp_outputccompdriverfile {
	my($filename) = @_;
	my $fh_ccompdriverfile;
	my $uapi_key;
	my $uapi_fndef;
	my $i = 0;

	open($fh_ccompdriverfile, '>', $filename) or die "Could not open file '$filename' $!";
	print $fh_ccompdriverfile "\n/* autogenerated XMHF composition driver file */";
	print $fh_ccompdriverfile "\n/* author: amit vasudevan (amitvasudevan@acm.org) */";
	print $fh_ccompdriverfile "\n\n";
	print $fh_ccompdriverfile "#include <xmhf.h>\r\n";
	print $fh_ccompdriverfile "#include <xmhf-debug.h>\r\n";
	print $fh_ccompdriverfile "#include <xmhfgeec.h>\r\n";
	print $fh_ccompdriverfile "\n\n";


	print $fh_ccompdriverfile "#include <xc.h>\r\n";
	#plug in header files
	while($i < $g_totalslabs){
	    print $fh_ccompdriverfile "#include <".$slab_idtoname{$i}.".h>\r\n";
	    $i=$i+1;
	}

	print $fh_ccompdriverfile "\n\n";


	#plug in frama-c nondeterminism
	print $fh_ccompdriverfile "\r\n//////";
	print $fh_ccompdriverfile "\r\n// frama-c non-determinism functions";
	print $fh_ccompdriverfile "\r\n//////";
	print $fh_ccompdriverfile "\r\n";
	print $fh_ccompdriverfile "\r\nu32 Frama_C_entropy_source;";
	print $fh_ccompdriverfile "\r\n";
	print $fh_ccompdriverfile "\r\n//@ assigns Frama_C_entropy_source \\from Frama_C_entropy_source;";
	print $fh_ccompdriverfile "\r\nvoid Frama_C_update_entropy(void);";
	print $fh_ccompdriverfile "\r\n";
	print $fh_ccompdriverfile "\r\nu32 framac_nondetu32(void){";
	print $fh_ccompdriverfile "\r\n  Frama_C_update_entropy();";
	print $fh_ccompdriverfile "\r\n  return (u32)Frama_C_entropy_source;";
	print $fh_ccompdriverfile "\r\n}";
	print $fh_ccompdriverfile "\r\n";
	print $fh_ccompdriverfile "\r\nu32 framac_nondetu32interval(u32 min, u32 max)";
	print $fh_ccompdriverfile "\r\n{";
	print $fh_ccompdriverfile "\r\n  u32 r,aux;";
	print $fh_ccompdriverfile "\r\n  Frama_C_update_entropy();";
	print $fh_ccompdriverfile "\r\n  aux = Frama_C_entropy_source;";
	print $fh_ccompdriverfile "\r\n  if ((aux>=min) && (aux <=max))";
	print $fh_ccompdriverfile "\r\n    r = aux;";
	print $fh_ccompdriverfile "\r\n  else";
	print $fh_ccompdriverfile "\r\n    r = min;";
	print $fh_ccompdriverfile "\r\n  return r;";
	print $fh_ccompdriverfile "\r\n}";

	print $fh_ccompdriverfile "\r\n\r\n";


	print $fh_ccompdriverfile "\r\n//////";
	print $fh_ccompdriverfile "\r\n// main function";
	print $fh_ccompdriverfile "\r\n//////";
	print $fh_ccompdriverfile "\r\n";
	print $fh_ccompdriverfile "void main(void){\r\n";

	# iterate over the uapi_fndef hashtable
	while ( ($uapi_key, $uapi_fndef) = each %uapi_fndef )
	{
		# fore each uapi_key we find, write function driver
		print $fh_ccompdriverfile "/* $uapi_key */\r\n";
		print $fh_ccompdriverfile "$uapi_fndrvcode{$uapi_key} \r\n\r\n";
	}

	print $fh_ccompdriverfile "}\r\n";

	close $fh_ccompdriverfile;
}
######
*)
	
let run () =
	Self.result "Generating composition check files...\n";
	uccomp_process_cmdline ();

	g_rootdir := (Filename.dirname !g_slabsfile) ^ "/";
	Self.result "g_rootdir=%s\n" !g_rootdir;

	umfcommon_init !g_slabsfile !g_memoffsets !g_rootdir;
	Self.result "g_totalslabs=%d \n" !g_totalslabs;
	
	uccomp_outputccompdriverfile ();
	
	Self.result "Done.\n";
	()


let () = Db.Main.extend run

