
/* --- this file is autogenerated --- */
/* uobjcoll/uobj sentinel code */
/* author: amit vasudevan (amitvasudevan@acm.org) */


/* --- sentinel code follows --- */




/* sentinel canonical name: uberspark__uobjcoll__platform__rpi3__uxmhf__uobjs__main___entry___uberspark__sentinels__init__armv8_32__baremetal__vccore__srot__generic__rpi3__hyp__call */
.section uberspark__uobjcoll__platform__rpi3__uxmhf__uobjs__main___entry___uberspark__sentinels__init__armv8_32__baremetal__vccore__srot__generic__rpi3__hyp__call

            /* sentinel size = 0x00001000 */
            ldr r0, = entry
            mov pc, r0
        




/* sentinel canonical name: uberspark__uobjcoll__platform__rpi3__uxmhf__uobjs__main___entry___uberspark__sentinels__pmethod__armv8_32__generic__generic__hyp__call */
.section uberspark__uobjcoll__platform__rpi3__uxmhf__uobjs__main___entry___uberspark__sentinels__pmethod__armv8_32__generic__generic__hyp__call

            ldr r3, = entry
            mov pc, r3
        

