#top-level Makefile for usr mode app (appnpf)
# author: amit vasudevan (amitvasudevan@acm.org)

.PHONY: all
all: 
	arm-linux-gnueabihf-gcc appnpf.c -o appnpf

.PHONY: clean
clean:
	rm -f appnpf
	rm -f *.o
	