#top-level Makefile for rich guest app, uhcalltest (rgapp-uhcalltest)
#  provides quick test functionality of hypervisor.
# author: amit vasudevan (amitvasudevan@acm.org)
# author: matt mccormack (matthew.mccormack@live.com)

.PHONY: all
all: 
	gcc -m32 rgapp-uhcalltest.c -o rgapp-uhcalltest

.PHONY: clean
clean:
	rm -f rgapp-uhcalltest
	rm -f *.o
